### ISSUE TITLE
Resize canvas easily?

### ISSUE THREAD

**Issue by jacauc** [slipx06/sunsynk-power-flow-card#10]
Hi @slipx06 

Do you know of a simple way to resize the canvas for the "lite" view with no solar installed so that is doesn't show blank whitespace at the top of the card?
Not a huge deal, just noticed it and thought it would be nice if the card was sized according to the contents.

![image](https://user-images.githubusercontent.com/18201320/235600822-609c63cb-12da-4d63-b0a5-3b5154296a9b.png)

**Comment by slipx06** [comment]
I don't think it can be done easily as I think the position of the SVG elements are relative to the canvas and they will all move out of alignment. I will take a look. Another option is to fill that space with some text i.e. card title or other information?

**Comment by slipx06** [comment]
I dont want to clutter the card but we can also extract the system timer info and display it 

![image](https://user-images.githubusercontent.com/7227275/235615561-f57876c7-2594-46d8-93d3-ac265a498af6.png)

**Comment by slipx06** [comment]
I can centre the svg elements 

![image](https://user-images.githubusercontent.com/7227275/235733235-a2215cf9-89c4-40da-9353-0d2c4170c8d1.png)

**Comment by slipx06** [comment]
I managed to figure it out. I'll push to master 

![image](https://user-images.githubusercontent.com/7227275/235796962-006ff4df-8152-4928-b057-b01067bd0f05.png)

**Comment by jacauc** [comment]
Stepped out for a couple of days. This is perfect thank you!
