### ISSUE TITLE
Litle mistake in documentation

### ISSUE THREAD

**Issue by mamo-nick** [slipx06/sunsynk-power-flow-card#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ssensor.sunsynk_day_battery_discharge

![mistake](https://github.com/slipx06/sunsynk-power-flow-card/assets/65286339/491b8899-8870-4f56-9491-26b79fcf064f)

### Expected behaviour

sensor.sunsynk_day_battery_discharge

### Card Version

3.1.0.

### Home Assistant Version

n/a

**Comment by slipx06** [comment]
Thanks I have fixed it.
