### ISSUE TITLE
remaining solar disappeared in release 3.0.0

### ISSUE THREAD

**Issue by adnovea** [slipx06/sunsynk-power-flow-card#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since version 3.1.0 the remaining solar energy has disappeared.
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/44359861/97121019-d191-436d-94dc-d54384e8bf4c)

### Steps To Reproduce

run the add-on

### Expected behaviour

Remaining energy not displayed

### Card Version

3.1.0

### Home Assistant Version

2023.10.5

**Comment by slipx06** [comment]
Hi. There was a breaking change in 3.0.0. You need to specific the display_mode for the solar information

- feat: new display_mode: for solar information. Values can be 1 - Only display the daily total, 2 - Display the daily total and remaining daily forecast, 3 - Display the daily total and total solar generation. The default value is 1.
-Example: Display Daily Total and Remaining Forecast

```
solar:
  display_mode: 2
```
