### ISSUE TITLE
Native goodwe support 

### ISSUE THREAD

**Issue by mamo-nick** [slipx06/sunsynk-power-flow-card#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No native goodwe support

### Expected behaviour

Hi,

Native goodwe support would be nice , so I prepared some information to help you.

### Possible Solutions

Read this file 
[goodwe.txt](https://github.com/slipx06/sunsynk-power-flow-card/files/13196365/goodwe.txt)

### Mode

lite

### Context / Reason

The context is in added file

**Comment by slipx06** [comment]
Thanks will take a look

**Comment by slipx06** [comment]
Added to [3.3.0](https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v3.3.0)
