### ISSUE TITLE
Not showing the power from grid

### ISSUE THREAD

**Issue by taHC81** [slipx06/sunsynk-power-flow-card#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I set the valid sensor for grid_power_169: sensor.electricity_usage_w , but it doesn't show it within the card.   day_grid_import_76: sensor.daily_grid_energy_sum is reported correctly.

### Expected behaviour

I'd expect to see the actual power taken from a grid.

### Card Version

3.3.0

### Home Assistant Version

core-2023.10.5

**Comment by taHC81** [comment]
Two pictures...
![Capture](https://github.com/slipx06/sunsynk-power-flow-card/assets/36913630/837851f0-9cf6-46f1-a56f-548cfa78525b)
![Capture2](https://github.com/slipx06/sunsynk-power-flow-card/assets/36913630/81832349-0334-4ceb-a3a2-242b677f4da8)

**Comment by slipx06** [comment]
Hi. The correct sensor is `grid_ct_power_172: sensor.electricity_usage_w`

**Comment by taHC81** [comment]
Thanks, now working fine. But it wasn't clear from the configuration docu.
