### ISSUE TITLE
EV SOC when using mdi:ev-station

### ISSUE THREAD

**Issue by amurray81** [slipx06/sunsynk-power-flow-card#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

EV Load and symbol

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/130550172/5a56c846-1b13-4c82-8f1c-27d76358431c)

### Expected behaviour

Could a display be added to show current vehicle SOC from a sensor entity?

### Possible Solutions

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/130550172/7b45fc31-e49d-40b3-8d17-d482ad90b231)

### Mode

Both

### Context / Reason

When glancing at the card you can see the vehicle SOC. Useful if using excess solar to top up EV charge
Allows all information to be displayed on 1 card

Love the card.
Thank you

**Comment by slipx06** [comment]
Hi. Yes you can show additional information for your loads by supplying sensors to the entities below. It is only displayed on the lite card due to space limitations. 

```
essential_load1_extra: | Optional |   | Sensor that contains additional information you want displayed for your essential load 1 e.g. Daily kWh, Temperature etc
essential_load2_extra: | Optional |   | Sensor that contains additional information you want displayed for your essential load 2 e.g. Daily kWh, Temperature etc
```


![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/7284f811-14e2-497a-b0f9-ddef4149dc3a)
