### ISSUE TITLE
Umstellungen und Kartengröße 

### ISSUE THREAD

**Issue by wartungsmonteur** [slipx06/sunsynk-power-flow-card#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hallo

Vielen Dank für das tolle Plugin. Wie ist es möglich dass man die Einheit Daily Aux von kWh auf W umstellen könnte ?

Wo kann man den Namen Essentiell und Daily Aux umstellen bzw. umbenennen ?

Könnte man die Karte insgesamt auch breiter machen ? Ich würde diese gern als Vollbild auf einem 12 Zoll Tablet darstellen wollen.

Vielen Dank und beste Grüße.

### Expected behaviour

Siehf meinen Text.

### Mode

full

### Context / Reason

Umstellungen und Kartengröße

**Comment by slipx06** [comment]
Hello

- No the card expects the daily values in kWh. You can create a template sensor to device by 1000. I think this was was discussed in one of the closed issues
- You cant change the name `Daily Aux`. I will add an option to change the essential name
- In order for the card to take up the full screen you should create a new dashboard and set the view type to panel (1 card). I've added a new attribute card_height that you can use to adjust the display. Will push this in the next version. 

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/a973f9b9-534a-4bf0-aa51-e7acf20d9fd6)
