### ISSUE TITLE
Senor or I'nputhelper as parameter for "height:"

### ISSUE THREAD

**Issue by ThomasReiter23** [slipx06/sunsynk-power-flow-card#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi!

Is it possible (or can you make it possible) to use a value from sensor or helper, to set the parameter for "height".
I want it to use for different dashboards in tablets and define specific heights for the dashboards and only the to set the one sensorvalue to denfine the height in all cards would be great.

### Expected behaviour

none

### Mode

Both

### Context / Reason

none

**Comment by slipx06** [comment]
Yes its possible. I'll add this to the next version
