### ISSUE TITLE
Add temperature to show aux

### ISSUE THREAD

**Issue by Legnava89** [slipx06/sunsynk-power-flow-card#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This feature is currently unavailable

### Expected behaviour

1.Please add a function to the sensors aux_load1 and aux_load2 to insert temperature sensors, if possible.

2. Fix a graphical problem with energy_cost_buy and energy_cost_sell in the card in the full version. see my screenshot

Thank you very much and I wish you and your family all the best.

### Possible Solutions

![Screenshot_20231104_212711_Home Assistant](https://github.com/slipx06/sunsynk-power-flow-card/assets/145229528/0a59d9c0-6136-4f65-9a3c-c4da5106a4b7)

### Mode

full

### Context / Reason

Just an idea. This function would be used a lot

**Comment by slipx06** [comment]
Your card is looking great 😄 
I'll take a look at both of those

**Comment by Legnava89** [comment]
Perfect job. You could move the spot price entity a little to the left so that it does not cover the entities from the grid

**Comment by slipx06** [comment]
I thought there was enough space when I tested it. Can you share a screenshot?

**Comment by Legnava89** [comment]
![Screenshot_20231105_190710_Home Assistant](https://github.com/slipx06/sunsynk-power-flow-card/assets/145229528/c88c4021-3f07-43b2-b972-0df4b383f120)

**Comment by Legnava89** [comment]
A little higher and it will be perfect :) 
Thank you very much.
![Screenshot_20231105_225809_Home Assistant](https://github.com/slipx06/sunsynk-power-flow-card/assets/145229528/bafc2258-bb91-43e3-896f-e9d26cfc32d2)

**Comment by slipx06** [comment]
Should be fixed in 3.9.0
