### ISSUE TITLE
Not displaying 0 value

### ISSUE THREAD

**Issue by mamo-nick** [slipx06/sunsynk-power-flow-card#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the value of  `grid_ct_power_xxx` = 0, value is not displaying.

![Snímek obrazovky 2023-11-06 175701](https://github.com/slipx06/sunsynk-power-flow-card/assets/65286339/d252de33-d4cf-44fb-95e7-f9aa1aaa0919)

### Expected behaviour

Displying O value as same as  `load_power_Lx:`

### Card Version

3.9.0

### Home Assistant Version

2023.10.0

**Comment by slipx06** [comment]
Thanks I've found the problem
