### ISSUE TITLE
hide grid

### ISSUE THREAD

**Issue by Privatecoder** [slipx06/sunsynk-power-flow-card#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

cannot see an option to hide the grid section, i.e. `show_grid: false` does not exist.

### Expected behaviour

there should be an option to hide the grid section with `show_grid: false`

### Possible Solutions

add `show_grid` option to hide the grid section

### Mode

lite

### Context / Reason

for off-grid installations, showing the grid section is useless

**Comment by slipx06** [comment]
Thanks for the suggestion. Will look into it

**Comment by Privatecoder** [comment]
@slipx06 almost perfect, however you would also want to hide `Autarky` and `Ratio` and make `grid_power_169` optional :)

**Comment by Privatecoder** [comment]
or leave `Autarky` (will be 100%) and `Ratio` (not sure how this is calculated) and make only `grid_power_169` either optional or settable to `0` (I currently just use a custom sensor which returns 0)

**Comment by slipx06** [comment]
You can hide Autarky by setting it to `no`. I'll fix the logic for grid_power when show_gird: false

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/da65d96d-ae42-4992-a3ee-6ec294e7465b)

**Comment by slipx06** [comment]
Have you tried setting `grid_power_169: none` ?

**Comment by Privatecoder** [comment]
yes – works fine. should update the docs regarding this parameter, i.e. `none` is a valid value

**Comment by slipx06** [comment]
Yes its optional so you should just delete. It says that in the docs
