### ISSUE TITLE
Essential load displayed wrongly

### ISSUE THREAD

**Issue by spopinski** [slipx06/sunsynk-power-flow-card#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot_20231109-091332398](https://github.com/slipx06/sunsynk-power-flow-card/assets/19770279/2563c3b0-fee2-4bd0-abbd-5050cee3bc96)

It's different when opened

![Screenshot_20231109-091339049](https://github.com/slipx06/sunsynk-power-flow-card/assets/19770279/51662509-cfa0-4713-a0dd-20271ccb6a4f)

### Expected behaviour

Should display the same as entity

### Card Version

V3.10.0

### Home Assistant Version

2023.9.1

**Comment by slipx06** [comment]
Looks like it might be an issue with the supplied sensor value. Please post a screenshot of your sensor from developer tools. It should be kWh

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/dee5147a-27bd-429a-b0ec-90f5ca4bd82e)

**Comment by spopinski** [comment]
It was working for months until now

![1123236](https://github.com/slipx06/sunsynk-power-flow-card/assets/19770279/2a25f6b6-b3c1-453d-bd8b-bc3795af5911)

**Comment by slipx06** [comment]
According to your screenshot the sensor value is 18932kWh. Which is what the card is displaying. I suspect you are capturing Wh and you need to convert to kWh. 18.9kWh

**Comment by spopinski** [comment]
Yes, what puzzles me that previously it's not a problem. Ok then consider case closed. Thanks a lot for this wonderful plugin!
