### ISSUE TITLE
Add non_essential_load3 to the grid

### ISSUE THREAD

**Issue by Legnava89** [slipx06/sunsynk-power-flow-card#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This function is not available

### Expected behaviour

Please add non_essential_load3: to the grid. I know there is limited space on the card, but I think it would work :)
Thanks in advance for your great work and patience with annoying users like me.

For information on how load3 would look on the card, see screenshot.

### Possible Solutions

![Screenshot_20231106_095656_Home Assistant](https://github.com/slipx06/sunsynk-power-flow-card/assets/145229528/8a2452eb-f10a-444c-96a2-0aaf638162ff)

### Mode

full

### Context / Reason

The possibility of using more home appliances and having a better overview of energy.

**Comment by slipx06** [comment]
Let me think about it 😄

**Comment by slipx06** [comment]
This will be a tight fit if you a or using all the card option

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/36444c35-f800-4f50-8171-79124feb300b)

**Comment by Legnava89** [comment]
I use a different style of battery layout than yours. It works very well for me.
![281751899-8a2452eb-f10a-444c-96a2-0aaf638162ff](https://github.com/slipx06/sunsynk-power-flow-card/assets/145229528/f0c4dfef-09fd-41d0-b50d-e854d0ce8301)

**Comment by slipx06** [comment]
Its because you dont define this entity `switch.sunsynk_toggle_system_timer`. I also need to think about all the other users of the card. It will only work if there is a conditional check to only show the 3rd load if this is false.

**Comment by Legnava89** [comment]
I understand. Unfortunately, I didn't realize that.
The only option is to move the cells to the right a little.

**Comment by slipx06** [comment]
I figured out how to do this. Will push in the next release. It will only display the 3rd load if you are not using the inverter timer schedules.

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/c48e1906-3e71-4f13-bba0-b296512436ab)

**Comment by Legnava89** [comment]
I don't use the inverter timer, I solve it with node red.
Thank you very much.
