### ISSUE TITLE
New entity grid_ct_power_total 

### ISSUE THREAD

**Issue by mamo-nick** [slipx06/sunsynk-power-flow-card#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In case of `three_phase: true` the grid_ct_power total value is calculated
After click on it, the  history of grid_ct_power_172 entity is displayed.

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/65286339/1cf93744-2330-45ff-ad13-15faa5b7a5aa)

### Expected behaviour

The rectangle is non-clickable like other calculated entities.

### Possible Solutions

1. The rectangle is non-clickable like other calculated entities.

and

2. Create a new entity for the sum of these entities. E.g. grid_ct_power_total - this entity is provided by goodwe integration and possibly others, or can be calculated in HA. Rectangle is clickable in this case. 

### Mode

Both

### Context / Reason

Correct display of values.

**Comment by slipx06** [comment]
Will fix this in the next release

**Comment by mamo-nick** [comment]
Retest OK. Thanks👍🏼
