### ISSUE TITLE
Goodwe Inverter Configuration Example - Update

### ISSUE THREAD

**Issue by mamo-nick** [slipx06/sunsynk-power-flow-card#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

outdated example

### Expected behaviour

I have updated the Goodwe inverter example to match the latest changes in the releases. I also added a few other sensors.
[goodwe.txt](https://github.com/slipx06/sunsynk-power-flow-card/files/13400743/goodwe.txt)

### Mode

lite

### Context / Reason

current example

**Comment by slipx06** [comment]
Thanks I have updated the example
