### ISSUE TITLE
add charge/discharge information for battery

### ISSUE THREAD

**Issue by MonsterD1** [slipx06/sunsynk-power-flow-card#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

no information for current charge/discharge load avaiable

### Expected behaviour

create a rectangel for the (chare/dischrge "W") for the battery
![Unbenannt_batt-watt](https://github.com/slipx06/sunsynk-power-flow-card/assets/66463436/a97422ed-92f2-4ac6-9a90-11dd461a6daf)

### Mode

lite

### Context / Reason

to be able to see the battery charge/discharge

**Comment by FajnB** [comment]
I think you might have miss-configured you card.
The charge/discharge power is in the rectangle next to the battery icon. (in yours it is that 0 W)

In my config and inverter when the battery is charging, the power is in negative value and vice versa.
Also there is an text what the battery is doing.

![obrazek](https://github.com/slipx06/sunsynk-power-flow-card/assets/65245546/53f5c53d-9450-46ed-8da4-b9e81b434053)

You might look into your yaml and configure `battery_power_190:` as shown [here on wiki](https://slipx06.github.io/sunsynk-power-flow-card/configuration.html#entities).

**Comment by MonsterD1** [comment]
thanks to your hint. I changed my config accordingly.
I just wondered why the battery (w) is not in an separat rectangle like on the grid power side, solar power side, load power side ... 
![Unbenannt_batt-watt](https://github.com/slipx06/sunsynk-power-flow-card/assets/66463436/22b4e420-bab2-4ff0-8684-298e02e91640)

**Comment by slipx06** [comment]
Hi. I prefer to keep all the battery information together. There is also not enough space when all the card options are enabled

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/453c0ba0-c911-4f16-adf7-c1e89303b353)
