### ISSUE TITLE
Change color on load

### ISSUE THREAD

**Issue by perjmolsen** [slipx06/sunsynk-power-flow-card#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have looked in the documentation, but I am unable to find the setting.

### Expected behaviour

I want the house to change color to the solor where the power comes from. 
Ex.. my solar panel color are orange, so if my solar panels are supplying the house load the color of the house has to be orange.
And also if I draw my house current from grid then, the house color changes to the grid color.
And last if I drwa my load from solar battery, then the house color need to change to the battery color.

It would be great if it where possible to mix the colors, so the hose has the % of color from the loads.

### Possible Solutions

Make some color settings :)

### Mode

lite

### Context / Reason

It would look great.
The card power-flow-card-plus has this option to change color, but it is not as great as sunsynk-power-flow-card

**Comment by slipx06** [comment]
Nice idea. Let me see what I can do

**Comment by perjmolsen** [comment]
Great, I am looking forward to try it, if it's possible :)

**Comment by slipx06** [comment]
I've added this to [3.17.0](https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v3.17.0). Give it a try 😄

**Comment by perjmolsen** [comment]
Is working GREAT! :) 
![Dynamic color](https://github.com/slipx06/sunsynk-power-flow-card/assets/126662740/2a0236ad-1815-4b0a-86fe-9fc007754f6f)
Thanks !

**Comment by bazcurtis** [comment]
I have just seen this in my dashboard. What a great idea.
