### ISSUE TITLE
Energy flow animation runs fast for NaN energy

### ISSUE THREAD

**Issue by herrfrei** [slipx06/sunsynk-power-flow-card#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the evening my OpenDTU devices show NaN as power. That results in fast animation on the card.

### Expected behaviour

No animated point

![Recording 2023-11-24 at 20 40 56](https://github.com/slipx06/sunsynk-power-flow-card/assets/11308345/602bb2ca-b2ca-4bfa-963e-9bc51f45ee9b)

### Card Version

3.17.0

### Home Assistant Version

2023.11.3

**Comment by slipx06** [comment]
What do those two sensors show as their state in HA?

**Comment by herrfrei** [comment]
The say 'Not available' ('Nicht verfügbar') in German.

slipx06 ***@***.***> schrieb am Fr., 24. Nov. 2023, 21:10:
