### ISSUE TITLE
Space for a Prepaid kWh entity

### ISSUE THREAD

**Issue by Sboshoff76** [slipx06/sunsynk-power-flow-card#155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

N/A

### Expected behaviour

N/A

### Possible Solutions

I use the lite card but I guess it could work on both. For those that keep track of their prepaid units within HA, would it be possible to add an extra entity either above or below the current grid indicator that shows your current unit balance? Similar to how you added the new temperature entity under the sun icon.

### Mode

Both

### Context / Reason

Thanks

**Comment by slipx06** [comment]
Hi. You should be able to use this sensor. 

`energy_cost_buy:`

**Comment by Sboshoff76** [comment]
But that's the cost per kwh, not so?

I'm talking about an entity that keeps track of how many kWh units you have
on your prepaid meter / account.

**Comment by slipx06** [comment]
Ok I've added it to both cards. The new entity is `prepaid_units:` 😄 

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/fe9ec7b3-a90b-41d0-8133-b9397797f8db) 
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/367c9b20-d6f8-43cf-8f94-8bc88ec8e3f0)

**Comment by slipx06** [comment]
Added to [3.21.0](https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v3.21.0)
