### ISSUE TITLE
FR translation update

### ISSUE THREAD

**Issue by adnovea** [slipx06/sunsynk-power-flow-card#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1- Grid is not translated
2- Autarky is not translated

### Expected behaviour

English text to replace by french translations

### Possible Solutions

1- Grid --> **Réseau**
2- Autarky --> Autarcie  (_or preferably **AutoConso** as this is the wording used by the french's administration when consuming your own production_)

### Mode

full

### Context / Reason

These are minor changes.
Many thanks for the frequent updates and the numerous features' additions.

**Comment by slipx06** [comment]
Thanks
