### ISSUE TITLE
Total solar generation for the day showing as MWh

### ISSUE THREAD

**Issue by wawyed** [slipx06/sunsynk-power-flow-card#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The last update changed total solar generation to MWh, this is fine if you want to show the total solar generation ever. But I was using that value to display the solar generation  forecast for the day. Would it be possible to add a mode to support it as well.

### Expected behaviour

Ability to display total  solar forescast for the day

### Card Version

4.0.0

### Home Assistant Version

2023.11.3

**Comment by slipx06** [comment]
I've added a new auto_scale function that is enabled for solar elements that should fix this.
