### ISSUE TITLE
CSS and Configuration options

### ISSUE THREAD

**Issue by devilliersjohnny** [slipx06/sunsynk-power-flow-card#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Absolutely adore the card... it has many if not most of the feature that a end-user could desire, however currently I was unable to  a way to style the card using CSS. I am working on a configuration menu that involves a few input_select and a few input_text options to aid in the configuration of the card.... Have most of the templating done to take W to kWh, added utility meters to track daily and monthly totals. However am currently unable to utilize the values of the afore mentioned within the top layer inputs

eg.
cardstyle: lite

Where lite would be a variable selected from an input_select

Oh before I forget... There was another item that caught my eye, there seems to be no ability to hide the degree symbol if there is no temperature input for the battery

### Expected behaviour

Manipulation of the the card using CSS or the ability to make the background transparent by any means that you find the easiest to implement... a solution to adding variables to the front-end, front-most options.

Attempted to input the state of my input_select sensor for my custom entity with no avail

cardstyle: |-
        {{ states["input_select.energy_db_card_style"].state }}

 The rest I can take care of, then finally the ability to hide the temperature input of the battery if none is provided

### Possible Solutions

The card-mod HACS feature by Tomas Loven would involve adding the ha-card class to the card, however this could potentially open a whole new can of worms. Look into the config template card  by Ian Richardson '@IANTRICH'.

Am definitely not the strongest coder but if there is anything that I can assist with please let me know

### Mode

Both

### Context / Reason

The whole Home Assistant environment is moving to the front-end having a way to manipulate the options for the card from there would make it allot more accessible, easier to use and almost universal ( It is almost already exactly that provided you provide the correct sensors with relevant information )

**Comment by slipx06** [comment]
Hi. Thanks for the positive feedback. This is not something I've looked at or familiar with. I'm open to ideas, suggestions or help. Maybe @Pho3niX90  knows?

> finally the ability to hide the temperature input of the battery if none is provided

I will take a look but you can delete the battery_temp_182 entity and it will remove the degree symbol

> Manipulation of the the card using CSS or the ability to make the background transparent by any means that you find the easiest to implement.

You should be able to manipulate the css elements below to adjust the card look. These are inherited from your theme but I assume you can use card-mod to set. I haven't really tried.
```

.card {
    border-radius: var(--ha-card-border-radius, 10px);
    box-shadow: var(--ha-card-box-shadow, 0px 0px 0px 1px rgba(0, 0, 0, 0.12), 0px 0px 0px 0px rgba(0, 0, 0, 0.12), 0px 0px 0px 0px rgba(0, 0, 0, 0.12));
    background: var(--ha-card-background, var(--card-background-color, white));
    border-width: var(--ha-card-border-width);
    padding: 0px;
    }
```
