### ISSUE TITLE
Ratio of house usage colour

### ISSUE THREAD

**Issue by Sboshoff76** [slipx06/sunsynk-power-flow-card#165]
Nevermind.. was an internal issue.

**Comment by Sboshoff76** [comment]
Sorry.. seems like it was not an internal issue

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/68126343/1f9cdcee-356c-4a68-b99a-ca01fa2753b9)

I currently have "use AC first" set, meaning all the grid will go into house and all the solar will go into battery, Yet the yellow house colour indicates otherwise.

**Comment by slipx06** [comment]
Hi. The card only considers power from the battery and solar and then proportions it based on measured house load. Any shortfall is assumed to be supplied from the grid.  Since you have configured a different priority it wont accurately reflect  your use case  and you should disable the feature.

**Comment by Sboshoff76** [comment]
Gotcha. Thanks for clearing it up
