### ISSUE TITLE
hybrid mode

### ISSUE THREAD

**Issue by amgstone** [slipx06/sunsynk-power-flow-card#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when the hybrid mode is on, the battery is charged from the sun and the house is supplied from the network, then a separate drawing is needed on the house so that it is clear that the house is not supplied by the sun.

### Expected behaviour

when the hybrid mode is on, the battery is charged from the sun and the house is supplied from the network, then a separate drawing is needed on the house so that it is clear that the house is not supplied by the sun.

### Possible Solutions

when the hybrid mode is on, the battery is charged from the sun and the house is supplied from the network, then a separate drawing is needed on the house so that it is clear that the house is not supplied by the sun.

### Mode

lite

### Context / Reason

![IMG_20231219_115231](https://github.com/slipx06/sunsynk-power-flow-card/assets/63303107/22e8aace-ead6-45b9-868c-fd7a31acf752)

**Comment by slipx06** [comment]
Hi. The implementation of the dynamic_icon and dynamic_colour is fairly simplistic. It only considers the essential_load and the battery and solar power. The card does not know what mode the inverter is running i.e. hybrid or if you are supplying loads in front of the inverter (non-essential).  I can perhaps build in another check that looks at the grid power i.e. PV power > essential_load power && battery power is < 5% of essential_power && grid power <5% of essential_power

If I look at your image you are supplying 1.6kW PV + 1.34kW Grid = 2.94kW supply but your load is only 1.1kW (Essential) + 968W (bat) = 2,06kW so you are missing some sensor data.

**Comment by amgstone** [comment]
yes, I have 2 batteries, but 1 is connected to HA

**Comment by slipx06** [comment]
I've added some additional checks for the next release to the dynamic_icon logic. It wont show the PV icon or the battery icon if the total_grid_power - Math.abs(nonessential) < 20

```
switch (true) {
            case pvPercentage_raw >= 100 && batteryPercentage_raw <= 5 && (total_grid_power - Math.abs(nonessential)) < 20 && config.load.dynamic_icon:
                essIcon = essPv;
                essIconSize = 1;
                break;
            case batteryPercentage_raw >= 100 && pvPercentage_raw <= 5 && (total_grid_power - Math.abs(nonessential)) < 20 && config.load.dynamic_icon:
                essIcon = essBat;
                essIconSize = 0;
                break;
            case pvPercentage_raw === 0 && batteryPercentage_raw === 0 && config.load.dynamic_icon:
                essIcon = essGrid;
                essIconSize = 0;
                break;
            default:
                essIcon = ess;
                essIconSize = 0;
                break;
        }
```

**Comment by slipx06** [comment]
The change discussed in #189 should fix this

**Comment by slipx06** [comment]
Fixed in https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v4.7.3
