### ISSUE TITLE
Essential / non essential issue

### ISSUE THREAD

**Issue by pawellygan** [slipx06/sunsynk-power-flow-card#19]
I think I have found one more problem with essential and non essential  measurments.

Essential is going to UPS which is connected to LOAD in the inverter.

My aux is deactivated as I don't need aux. I use UPS (in case of power cut essential load will stay powered from battery)

![IMG_7596 2](https://github.com/slipx06/sunsynk-power-flow-card/assets/45388740/dca72032-72e7-491a-bd0f-cc6f367c4397)

It how it looks from an integration point of view:
<img width="332" alt="Screenshot 2023-05-10 at 14 13 48" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/45388740/476d7dff-b9fd-4553-92d4-83f39e1af149">

now let's take your calculation for Essential load:

"essential = inverter_out_175 - (aux_power_166 - inverter_load_grid_169 )"

X = 500 - ( 0 - 500)
X = 500 + 500
X=1000

That is wrong.

<img width="523" alt="Screenshot 2023-05-10 at 14 21 21" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/45388740/4a2faa85-0af9-434c-ad65-e8b8f1ccb052">

My Essential load now is 0W in reality 
Also, non essential load should be a positive value IMHO

EDIT: Wanted to add that my Sunsynk is integrated with HA via Solar Assistant and MQTT Broker

**Comment by slipx06** [comment]
You need to check which modbus rgisters Solar Assistant is using. Have a look at the inverter screen below.  The card is based on this logic. The only change I made was update 167 with 169 = 167+168.  inverter_out_175 is not the same as inverter_load_grid_169. They are different measurement points. 

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/c52bf23e-9c67-4175-b50d-e0816a702cd5)
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/247062bc-c9be-4d38-af97-6ac57a4a353d)

**Comment by slipx06** [comment]
Yes but remember that register 175 can be both positive or negative i.e. when charging batteries

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/636ccc29-aad4-4bd2-a966-2138674cc065)

**Comment by pawellygan** [comment]
I'm still trying to understand that. I wrote email to SA with a question what is GRID LD

**Comment by pawellygan** [comment]
Ok it looks like SA is doing this inside - it has a sensor NON-ESSENTIAL-LOAD

<img width="638" alt="Screenshot 2023-05-10 at 16 22 04" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/45388740/f295a89c-4922-426d-9043-feb3cc0fdac2">

**Comment by pawellygan** [comment]
that means when I use SA in between SunSynk and HA I can't use your card as

essential:
<img width="560" alt="Screenshot 2023-05-10 at 16 41 51" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/45388740/84f44074-9b30-490c-9a82-d830ab0a2ecb">

and non-essential:

<img width="596" alt="Screenshot 2023-05-10 at 16 42 33" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/45388740/30ab6681-a699-403d-b730-b77eb48bd34d">

Are exposed straight from SA as a separate entities.
The only option is somehow to skip your attributes:

nonessential = grid_external_power_172 - inverter_load_grid_169
essential = inverter_out_175 - (aux_power_166 - inverter_load_grid_169 )

and provide sensor etities for both values without doing 175-(166-169) as this is done inside SA already.

**Comment by slipx06** [comment]
I could add the non-essential and essential sensor options to the card config and if they are set to 'internal' it uses the internal card logic to calculate otherwise the supplied sensor data

**Comment by pawellygan** [comment]
> I could add the non-essential and essential sensor options to the card config and if they are set to 'internal' it uses the internal card logic to calculate otherwise the supplied sensor data

this!!!

**Comment by slipx06** [comment]
non-essential and essential can now be specified through the card configuration. Setting these values to none uses the old logic. See v1.3.5
