### ISSUE TITLE
battery

### ISSUE THREAD

**Issue by amgstone** [slipx06/sunsynk-power-flow-card#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have an easun inverter, when the battery is not charged, the consumption from the battery reaches 100 watts. and at night it shows a mixed mode that consumption comes from both the battery and the network. perhaps it is worth doing as with solar panels, if the consumption is up to 100 watts, then show 0 consumption.

### Expected behaviour

I have an easun inverter, when the battery is not charged, the consumption from the battery reaches 100 watts. and at night it shows a mixed mode that consumption comes from both the battery and the network. perhaps it is worth doing as with solar panels, if the consumption is up to 100 watts, then show 0 consumption.
![IMG_20231222_000428](https://github.com/slipx06/sunsynk-power-flow-card/assets/63303107/03856873-c676-4b9e-9c3d-f3a9ee01dcfa)

### Mode

lite

### Context / Reason

I have an easun inverter, when the battery is not charged, the consumption from the battery reaches 100 watts. and at night it shows a mixed mode that consumption comes from both the battery and the network. perhaps it is worth doing as with solar panels, if the consumption is up to 100 watts, then show 0 consumption.

**Comment by slipx06** [comment]
I can look at increasing the thresholds for both the dynamic_colour and dynamic_icon. 
For dynamic colour I can ignore anything that is not > 2% of load
Similarly when both PV and bat are less than 5% of load assume supply from grid and show the correct icon. This is currently triggered when both  are 0%
It should address your issue. Will have to test it

**Comment by amgstone** [comment]
super
