### ISSUE TITLE
Battery Remain Energy kWh

### ISSUE THREAD

**Issue by matomatusov** [slipx06/sunsynk-power-flow-card#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

addition to the battery

### Expected behaviour

Hi,
it would be possible to add to the battery part of the entity Battery Remain Energy  (kWh) ?
![battery](https://github.com/slipx06/sunsynk-power-flow-card/assets/129114957/b363a527-da69-4ab8-b072-4eea0f0ff9cc)

Thanks :)

### Mode

compact, lite, full

### Context / Reason

better idea how many kWh are in the battery

**Comment by matomatusov** [comment]
Hi,
couldn't the text be moved down a bit?

![battery_2](https://github.com/slipx06/sunsynk-power-flow-card/assets/129114957/b92a69e7-3f36-430c-b771-1c1b983ff22c)

**Comment by slipx06** [comment]
When using the default card_height there is no space to move this lower (See images below). It looks like you have adjusted the card_height? The only solution is to reposition the battery elements higher.
 
Default card height
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/67c99fb5-ca69-4263-a933-0c6670013938)

Adjusted card height
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/4dc1b236-ca66-4c69-a8b0-b7467759a507)

**Comment by matomatusov** [comment]
Hi,
I have the height of the card in the default state. 
would it be possible to move the battery up here?
would it be possible to display the voltage on the battery cells?
see image.
![battery_3](https://github.com/slipx06/sunsynk-power-flow-card/assets/129114957/1c1a277b-d3a7-4bdc-82be-4a53bb6fe353)

**Comment by slipx06** [comment]
> would it be possible to move the battery up here?

Yes I will make a small adjustment

> would it be possible to display the voltage on the battery cells?

Not planned but will keep on the feature list
