### ISSUE TITLE
Time Of Use Tabel 

### ISSUE THREAD

**Issue by Mights001** [slipx06/sunsynk-power-flow-card#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, can i activated somewhere this Datapoints in the Card? 

![grafik](https://github.com/slipx06/sunsynk-power-flow-card/assets/35522918/9a8087c2-da38-47d6-a1c0-60da8764ca28)

### Expected behaviour

.

### Card Version

4.10.1

### Home Assistant Version

2024.1.3

**Comment by slipx06** [comment]
Its not displayed on the card, but you can create a separate card. I have two examples you can refer to here https://github.com/slipx06/Sunsynk-Home-Assistant-Dash

Example 1
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/86a82f69-3aad-42ff-ac4e-f25f03c1522c)

Example 2
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/323acce0-af88-4201-acbf-076a66e066f1)

**Comment by Mights001** [comment]
Thank you very much
