### ISSUE TITLE
Inconsistency in decimal place for phases voltages in compact card style

### ISSUE THREAD

**Issue by FajnB** [slipx06/sunsynk-power-flow-card#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The compact card style has its phase voltages not rounded.

### Steps To Reproduce

1. Create card.
2. Set card style to compact
3. Add voltages for phases
4. Observe that the voltages are shown as floats

Compact:
![obrazek](https://github.com/slipx06/sunsynk-power-flow-card/assets/65245546/8c482c04-a345-49dc-aa22-2c788e4b6d96)

Lite:
![obrazek](https://github.com/slipx06/sunsynk-power-flow-card/assets/65245546/a3f4eece-5e01-4907-bb65-89c91820d5e2)

Full:
![obrazek](https://github.com/slipx06/sunsynk-power-flow-card/assets/65245546/6af47c22-9071-402f-a225-33be63813b9c)

### Expected behaviour

Based on fact that:
1. Lite card style was introduced first and has this set to be rounded
2. And also the fact, that for users with 3-phase inverters, the text will runoff under other information on the card

I think, that the voltages should be also rounded for the Compact card style.

### Card Version

4.10.2

### Home Assistant Version

2023.11.3

**Comment by slipx06** [comment]
Hi. Thanks for catching that. I will fix it.
