### ISSUE TITLE
Battery Options - SOC

### ISSUE THREAD

**Issue by matomatusov** [slipx06/sunsynk-power-flow-card#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It wouldn't have to change here if SOC changes.

### Expected behaviour

Question to battery options. Would it be possible to enter an sensor here?
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/129114957/9b8ab250-0d7e-445d-a544-8677eb4b1be7)

### Mode

Both

### Context / Reason

It must be rewritten if there is a change.

**Comment by slipx06** [comment]
Hi Yes you can provide a sensor for this but need to switch to the code editor and add it.

**Comment by matomatusov** [comment]
Hi, thank you, I didn't think of that.
