### ISSUE TITLE
Daily Load not visible in full mode

### ISSUE THREAD

**Issue by creuter27** [slipx06/sunsynk-power-flow-card#24]
In the "full" mode the se"show_daily" under load doesn't seem to change anything.
I would like to be able to see the daily consumption of the house (connected to the load terminal).

**Comment by creuter27** [comment]
I just realized that the value is visible if "show_aux" is set to "no".
That solves it for me as I don't need the aux value but that may not be the case for everyone.

**Comment by slipx06** [comment]
Yes I need to relook at that and see if we can reposition the daily values when Aux is enabled

**Comment by slipx06** [comment]
Fixed in 1.5.1. Thanks for the feedback.
