### ISSUE TITLE
Daily Totals are first being rounded to an Integer and so always have a Zero decimal

### ISSUE THREAD

**Issue by MikeRobertson** [slipx06/sunsynk-power-flow-card#25]
Just a "Heads Up" with your recent update of "All daily Totals have been rounded to 1 decimal place"

For Daily totals (and, indeed, elsewhere although I don't know the impact) you have used **parseInt(stateObj.state).toFixed(1)**

instead of **parseFloat(stateObj.state).toFixed(1)**

This causes the number to be converted to an Integer before being rounded to a fixed single decimal place thus resulting in always having a zero decimal number shown.

Thanks otherwise for an excellent power flow card!

**Comment by slipx06** [comment]
Thanks for that. Will push an update to fix
