### ISSUE TITLE
Values not being rounded

### ISSUE THREAD

**Issue by chickenbeef** [slipx06/sunsynk-power-flow-card#27]
Running v1.5.3 and values are randomly not being rounded. Example:

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/11455025/ada1b9e7-6b83-4343-b7a2-5ee999e979ab)

Another example: https://mybroadband.co.za/forum/threads/sunsynk-home-assistant.1183858/post-31279011

For these, I see that there's no rounding (`.toFixed`) here:

https://github.com/slipx06/sunsynk-power-flow-card/blob/f1b58e2816bc0b69088ca84945b3eed29b88031a/dist/sunsynk-power-flow-card.js#L160-L196

Could that be the issue?

**Comment by slipx06** [comment]
This should be fixed in 1.5.4. Thanks
