### ISSUE TITLE
Net Battery Watt

### ISSUE THREAD

**Issue by ngoyat** [slipx06/sunsynk-power-flow-card#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When battery is charging , line are moving from inverter to battery but Watt are displayed -ve. 

### Expected behaviour

I assume when we put charge in battery input watt must be shown as positive number where as on battery discharge watt number must be negative

### Card Version

v4.16.1

### Home Assistant Version

2024.2.2

**Comment by slipx06** [comment]
battery_power_190: | Required | sensor.sunsynk_battery_power | Battery power (W). Requires a negative number for battery charging and a positive number for battery discharging. Set the invert_power: battery attribute to yes if your sensor reports this the other way around
