### ISSUE TITLE
Add Show Remaining Energy (and Battery Status) into Lite and Full Cards

### ISSUE THREAD

**Issue by Roving-Ronin** [slipx06/sunsynk-power-flow-card#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi Slipx06,

Currently the Show Remaining Energy is not shown on the Lite / Full cards if you have the  battery_status: filled in.
Just looking at both cards and wondering if it could be added in to show both battery_state and show_remaining_energy ?

### Expected behaviour

Show both entities, if both have a sensor assigned to provide the data, in the Lite and Full Card

### Possible Solutions

In the lite card it appears theirs space to include it (see yellow boxes) potentially:

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/108674933/7586b53c-c154-4b41-b8ed-ea461cdb18e9)

In the full card, there's these spaces that are left void and could potentially be used ?

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/108674933/e78b6447-5691-4656-bbca-ed1f9427023f)

### Mode

Both

### Context / Reason

Handy to know the actual kWh you have left in the battery, versus just a %.

**Comment by Roving-Ronin** [comment]
@slipx06 Thanks !

**Comment by fraserallanuk** [comment]
I would love this to be added to the Compact card also, if possible? @slipx06
