### ISSUE TITLE
Feature Request - add temperatures

### ISSUE THREAD

**Issue by creuter27** [slipx06/sunsynk-power-flow-card#28]
Hi slipx06,
I think it would also make sense to add the inverter heat sink temperature and the battery temperature. The inverter's Modbus output provides both.

PS: I opened a new issue for this request just so it doesn't get lost. Should be quite easy to implement if you can find some space for it.

**Comment by slipx06** [comment]
Added to v1.5.6 :)

**Comment by Papsnoek** [comment]
Ah, you beat me to it, I was almost done testing my version :)
Time to go compare notes :P

**Comment by Papsnoek** [comment]
Just FYI, this is how my implementation looks. I do however prefer yours :)
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/3797281/c7ae748d-587f-42ff-8f82-54f88d5919c3)

**Comment by slipx06** [comment]
The thing is not everyone would want to display them.

**Comment by Papsnoek** [comment]
yeah, I did make it optional, so if not displayed, then it would go back to original with only Power and Amps. I do like your design better through, much smaller, and I didnt add the battery temp like you did.

FYI: Thanks for creating this Card, its pretty darn amazing ;)
