### ISSUE TITLE
C02

### ISSUE THREAD

**Issue by ad2381** [slipx06/sunsynk-power-flow-card#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

no CO2 carbon footprint

### Expected behaviour

Is it possible to show on the sunsynk card the C02 footprint. It is already possible to use the electricitymaps API in the existing HA energy dashboard so the entities are present.

### Possible Solutions

use existing integration https://app.electricitymaps.com/map

### Mode

Both

### Context / Reason

nice to have

**Comment by slipx06** [comment]
Interesting but I'd say that this falls outside the scope of the card. If you are up to it create a fork and give it a go
