### ISSUE TITLE
add show_remaining_energy: to compact card

### ISSUE THREAD

**Issue by amgstone** [slipx06/sunsynk-power-flow-card#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

add show_remaining_energy: to compact card

### Expected behaviour

add show_remaining_energy: to compact card

### Possible Solutions

add show_remaining_energy: to compact card

### Mode

lite

### Context / Reason

add show_remaining_energy: to compact card

**Comment by slipx06** [comment]
Thanks I saw this. Pushing a fix now
