### ISSUE TITLE
color flow from inverter to load 

### ISSUE THREAD

**Issue by jolly12f** [slipx06/sunsynk-power-flow-card#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

now the flow has a static color 

### Expected behaviour

the stream should be colored like the load icon 

### Possible Solutions

all 

### Mode

Both

### Context / Reason

make the flow from inverter to load dynamically colored like the load icon

**Comment by slipx06** [comment]
Hi. That line is made up of two SVG path elements and applying a gradient affect to each of these will not have the intended affect. For now its only the icon the is dynamically coloured.
