### ISSUE TITLE
No Grid - Line through it

### ISSUE THREAD

**Issue by EddieSpaghettie** [slipx06/sunsynk-power-flow-card#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If  grid is off it doesnt show.

### Expected behaviour

There used to be a line through the grid image when grid was offline. Id like that back

### Mode

Both

### Context / Reason

Cause only way to see its off is when it shows not normal

**Comment by slipx06** [comment]
Please see #319
