### ISSUE TITLE
grid icon overlay 

### ISSUE THREAD

**Issue by Hitman79** [slipx06/sunsynk-power-flow-card#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As soon as the net switches from import to export, the symbols overlap. What could be the reason for this, do I have the wrong setting?
![Screenshot 2024-03-20 110308](https://github.com/slipx06/sunsynk-power-flow-card/assets/101149246/555dcc8b-abff-46b0-adac-e0973d07e923)
![Screenshot 2024-03-20 110327](https://github.com/slipx06/sunsynk-power-flow-card/assets/101149246/e9fd3099-5e30-43c3-8d5a-b1bb7c3734f3)

### Expected behaviour

the icons must be hidden while changing

### Card Version

 v4.24.1

### Home Assistant Version

2024.3.1

**Comment by slipx06** [comment]
What sensor are you using for `grid_connected_status_194:`

**Comment by slipx06** [comment]
I've added better handling of this in https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v4.24.2.
Make sure you sensor provides on of the expected values otherwise if will default to the connected state

```
export const validGridDisconnected = ['off', '0', 'off-grid', 'off grid', 'offgrid']
export const validGridConnected = ['on', '1', 'on-grid', 'on grid', 'ongrid']
```

**Comment by EddieSpaghettie** [comment]
When my Grid is off it doesnt have a line through it. It used to have it but stopped a while back. Maybe its checking incorrect parameter on Lux inverter

**Comment by EddieSpaghettie** [comment]
Just upgraded to the new version. Luxpower inverter. As you can see grid is at 0V etc. I turned the main switch off and it doesnt make a line through the grid : Only getting the Alarm Notification. IS there anything else that needs to be set perhaps?
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/58969883/1a910db2-f2c8-4aa9-b8dd-f68ec279f369)

**Comment by EddieSpaghettie** [comment]
ok got it right. made a binary sensor to check status

**Comment by Hitman79** [comment]
> What sensor are you using for `grid_connected_status_194:`

I currently have no sensor set because I read out my inverter via SolarAssistant (MQTT), which unfortunately does not have a status sensor that I need here. I have to build a helper here. Thanks for your support

**Comment by Hitman79** [comment]
I no longer have any problems with the latest version v4.24.4. Thank you very much
