### ISSUE TITLE
Display 3 additional loads

### ISSUE THREAD

**Issue by gibber666** [slipx06/sunsynk-power-flow-card#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Only 2 or 4 additional loads can be displayed.

### Expected behaviour

Display of 3 additional loads should also be possible.

### Possible Solutions

Could be done by using the same layout as it is with 4 additional loads, but show only 3.
<img width="487" alt="Bildschirmfoto 2024-03-30 um 09 59 56 1" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/147249673/6a8fdf62-148f-40bb-93c4-59b0d8d5cd7b">

### Mode

Both

### Context / Reason

I  have 3 additional loads and want to display these 3.
It would be great if you would allow to display 3 additional loads.

**Comment by slipx06** [comment]
Hi. This has been added to https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v4.26.0
