### ISSUE TITLE
Ability to change description.

### ISSUE THREAD

**Issue by Gorwanvfr** [slipx06/sunsynk-power-flow-card#35]
It would be great if the description of Non Essential and Auxiliary could be changed to whatever the user desired. 
Thanks

**Comment by amctear** [comment]
Apologies for my comments if it upsets,  it’s such a great piece of work let’s just appreciate the grace & splendour that has been gifted to us.  Pivot and transition springs to mind ☀️

Call it what you want, it’s great work🙏

On 2 Jun 2023, at 22:25, Gorwanvfr ***@***.***> wrote:

﻿

It would be great if the description of Non Essential and Auxiliary could be changed to whatever the user desired.
Thanks

**Comment by slipx06** [comment]
Thanks for the suggestion. There is a feature request to to this as well as support additional loads on the essential, aux and non-essential. Its on the TO-DO list :)

**Comment by slipx06** [comment]
Hi. This has been introduced in v1.6.2
