### ISSUE TITLE
Add PowMr Inverter Support

### ISSUE THREAD

**Issue by Roving-Ronin** [slipx06/sunsynk-power-flow-card#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Add support for PowMr inverters https://powmr.com/ a PIP type inverter, by the addition of an image file, suggest

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/108674933/30daaae1-e4f6-42f8-b9c7-ba862712b7e4)

from: https://powmr.com/cdn/shop/files/1600Watt220Vac12VdcAllInOneInverterCharger-1.jpg?v=1692683840&width=800

### Expected behaviour

As per other inverters. Data from the PowMr inverters being provided by the following integration: https://github.com/odya/esphome-powmr-hybrid-inverter

### Possible Solutions

Integration developer has already mapped his outputs to be compatible with SunSynk card, 
See example at: https://github.com/odya/esphome-powmr-hybrid-inverter/blob/main/examples/inverter-card-example.yaml

### Mode

Both

### Context / Reason

Cater for additional inverter brand(s).

**Comment by slipx06** [comment]
Added to https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v4.27.0
