### ISSUE TITLE
Extra info for aux load

### ISSUE THREAD

**Issue by virtualj** [slipx06/sunsynk-power-flow-card#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, I use aux load for wallbox and to have extra info with car battery percentage I need to configure 1 extra aux load. This situation cause a reduntant info about the power (same value) and the icon of the extra load does not reflect the aux disconnected colour. This is the actual view:
![immagine](https://github.com/slipx06/sunsynk-power-flow-card/assets/4136881/25e8c0e4-aab3-42f2-83d3-c91383057e24)

### Expected behaviour

Will be usefull to have the extra info also when there is no extra load or the extra load is only one, like this:
![immagine](https://github.com/slipx06/sunsynk-power-flow-card/assets/4136881/04dbeaf6-56bc-481b-9957-3f16e21bc6f2)

### Mode

full

### Context / Reason

I think that configuration with only one aux is tipical and the extra info can be usefull to much people.
Thank you!

**Comment by slipx06** [comment]
Thanks for the suggestion. Its possible to add this. May need to shrink the AUX icon to make space. Will take a look

**Comment by slipx06** [comment]
Added to https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v4.28.0

**Comment by Roving-Ronin** [comment]
@slipx06 is seems that this change and its not showing aux\_load1\_extra unless aux\_loads: = 0, also means that where AUX is used for >0 that only aux\_load2\_extra will be shown. :-(

pre v4.280.0

![](https://github.com/slipx06/sunsynk-power-flow-card/assets/108674933/52d7bdb6-befa-4e2f-be85-0572031f34d8)

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

post updating to v4.280.0

![](https://github.com/slipx06/sunsynk-power-flow-card/assets/108674933/bd0a46fb-7774-4019-826a-54de884bf28b)

**Comment by slipx06** [comment]
@Roving-Ronin sorry about that. Pushed a fix in [4.28.1](https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v4.28.1)
