### ISSUE TITLE
Add 2 extra batteries

### ISSUE THREAD

**Issue by github-daniel-stoian** [slipx06/sunsynk-power-flow-card#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently we can add additional_loads up to 4 in Compact mode, which is very beneficial to see more important consumers in the schema.
<img width="1041" alt="Screenshot 2024-04-14 at 21 57 18" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/26714611/f363e220-b529-4afa-8047-1670cd05e118">

### Expected behaviour

I currently have 2 x Ecoflow DeltaPro which are charged via AC-IN from a Huawei 6KW inverter.
Even if they are not directly connected to Inverter DC batt, they are still part of the ecosystem powering the house during the night.

It will be more suitable to place them as additional_batteries up to 2 with SOC, Voltage, Power like normal batteries.
This is beneficial to free up the additional_loads slots for other consumers.
<img width="1061" alt="drawing1" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/26714611/e8c828b8-af0b-49be-8abf-3f726f646b68">

### Possible Solutions

In Compact you can specify:
On battery section : additional_batteries 2
On entities section : 
battery_power_extra1
battery_voltage_extra1
battery_soc_extra1

battery_power_extra2
battery_voltage_extra2
battery_soc_extra2

### Mode

lite

### Context / Reason

It will help to integrate external batteries in the energy flow

**Comment by github-daniel-stoian** [comment]
I could create extra 2 cards and place one Ecoflow on one card.

In this case:
-I will have 3 energy cards: hard to arrange on a dashboard, extra management of code
-Ecoflow cards won't have solar, because I don't charge them from solar, only from AC provided by Growatt
-Ecoflow cards mainly will show the battery pictures with SOC, power, voltage ... grid, solar will not be used.

That's why I think they could fix better as additional_batteries in the Huawei inverter card.

**Comment by slipx06** [comment]
Hi. Thanks for the suggestion. It's on the to-do list together with multi inverter setups

**Comment by github-daniel-stoian** [comment]
Thank you very much. Very good work you are doing.
Probably the ultimate/one Energy card needed on HA.

**Comment by Roving-Ronin** [comment]
> Hi. Thanks for the suggestion. It's on the to-do list together with multi inverter setups

Hi @slipx06 any update on this ? I know its a bit of a 'how longs a piece of string question', given time in the day and things to do ;-)

**Comment by slipx06** [comment]
Thinking about this more, why not just use two cards next two each other (one for each inverter).

**Comment by slipx06** [comment]
Carry on here https://github.com/slipx06/sunsynk-power-flow-card/discussions/374
