### ISSUE TITLE
Added SMA Inverter Model

### ISSUE THREAD

**Issue by shingsam** [slipx06/sunsynk-power-flow-card#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
![Inverter SMA Sunny Tripower](https://github.com/slipx06/sunsynk-power-flow-card/assets/35526270/56f2d0e5-c43b-4901-a77f-9bfe2d78a1e7)
![SMA Sunnyboy](https://github.com/slipx06/sunsynk-power-flow-card/assets/35526270/5dc0d8cc-54fa-4e4d-a3f4-17a17ed7cab5)
![SMA Sunny Tripower Smart energy inverter](https://github.com/slipx06/sunsynk-power-flow-card/assets/35526270/45aa1482-2fa6-4267-8346-c47f57ca58b7)
![SMA Sunny Island](https://github.com/slipx06/sunsynk-power-flow-card/assets/35526270/b414414c-e165-4499-9991-42d110db5074)

Please add SMA Inverter Model.

### Expected behaviour

SMA Inverter model have SMA Sunny Island (Yellow), SMA Sunny Boy (Red), SMA Sunny Try Power (Blue), and SMA Sunny Tripower Smart Energy (White).
I have sample img SMA Sunny Island (Yellow) (https://raw.githubusercontent.com/shingsam/SMAVenusDriver/master/assets/overview-inverter.svg)

### Possible Solutions
The SMA Solar integration will poll a [SMA](http://www.sma-solar.com/) [(US)](https://www.sma-america.com/) solar inverter, energy meter or battery inverter and present the values as sensors in Home Assistant.
https://www.home-assistant.io/integrations/sma/

### Mode

Compact, Lite, Full

### Context / Reason

Many people use your components, and they have different inverter brands.

**Comment by paolotacc** [comment]
Can you integrate ABB Power one inverter ?

**Comment by shingsam** [comment]
> Can you integrate ABB Power one inverter ?

No, i cant.

**Comment by slipx06** [comment]
Can you share some of the inverter status messages that the integration provides

**Comment by shingsam** [comment]
> Can you share some of the inverter status messages that the integration provides

35: Fault (Alm), 303: Off (Off), 307: Ok (Ok), 455: Warning (Wrn)

**Comment by slipx06** [comment]
Hi. Added to https://github.com/slipx06/sunsynk-power-flow-card/releases/edit/v4.32.0
