### ISSUE TITLE
GEN input

### ISSUE THREAD

**Issue by juanka99** [slipx06/sunsynk-power-flow-card#39]
Hi!
It could be possible to use a microinverter production connected to GEN input?
Thanks.

**Comment by slipx06** [comment]
Hi. Yes the card already supports this. Its the AUX connection that accepts input from GEN/Microinverter or it can also be used to supply a load. Have a look at the following attributes under Load and setup according to your needs:
<html>
<body>


Attribute | Requirement | Default | Description
-- | -- | -- | --
show_aux: | Optional | no | Toggles the display of Aux (yes/no)
invert_aux: | Optional | no | Set to yes if your sensor provides a positive number for AUX input and negative number for AUX output
aux_name: | Optional | Auxilary | Set the display name for the Auxilary Load


</body>
</html>
