### ISSUE TITLE
general options - show grid - decimal places

### ISSUE THREAD

**Issue by matomatusov** [slipx06/sunsynk-power-flow-card#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

hi,
2 decimal places should be displayed
![2](https://github.com/slipx06/sunsynk-power-flow-card/assets/129114957/96d190c8-b769-4467-8327-534592b0ec6f)

### Expected behaviour

display the number of decimal places according to the setting.

### Card Version

4.30.1

### Home Assistant Version

2023.12.2

**Comment by slipx06** [comment]
Hi. Daily energy values are rounded to one decimal place


auto_scale: | Optional | true | If set to true the card will use the entities unit_of_measurement attribute to perform the correct scaling (i,e, power values greater than 999W will be displayed as kW e.g. 1.23kW) and display the correct unit. The number of decimal places can be changed using the decimal_places card attribute apart from the daily energy values which are rounded to 1 decimal place
-- | -- | -- | --

**Comment by matomatusov** [comment]
Hi,
and wouldn't it be possible to have 2 decimal places?

**Comment by slipx06** [comment]
It's not part of the current energy conversion function. It would require some code changes but not sure its worth the effort.

**Comment by slipx06** [comment]
@matomatusov I've added a new attribute (`decimal_places_energy`) in the latest release that lets you set the number of decimal places displayed for the daily energy values. 
https://github.com/slipx06/sunsynk-power-flow-card/releases/edit/v4.32.0

**Comment by matomatusov** [comment]
Hi,
thanks for implementing those decimal places for energy.
