### ISSUE TITLE
Autarky/Ratio issues 

### ISSUE THREAD

**Issue by elRadix** [slipx06/sunsynk-power-flow-card#42]
Hi @slipx06
Using the latest avaliable version of your card still notice some issues
The value can't be negative and can't exceed 100%

Can you please check?

some information:
https://www.npro.energy/main/en/help/self-sufficiency-rate

![IMG_20230621_111955_474](https://github.com/slipx06/sunsynk-power-flow-card/assets/6258894/15654d67-fb60-4a88-bd5b-f82c2d714065)

**Comment by slipx06** [comment]
Are you sure you are running the latest version and cleared your cache. Version 1.7.5 uses the formula below

```
    let production_p = parseInt(totalsolar) + parseInt(`${battery_power > 0 ? battery_power : 0}`) + parseInt(`${aux_power < 0 ? aux_power * -1 : 0}`);
    let consumption_p = parseInt(essential) + parseInt(nonessential) + parseInt(`${aux_power > 0 ? aux_power : 0}`) + parseInt(`${battery_power < 0 ? battery_power * -1 : 0}`);
    let Autarkyp = consumption_p != 0 ? Math.min(Math.round((production_p * 100) / consumption_p), 100) : 0;
    let Ratiop = production_p != 0 ? Math.min(Math.round((consumption_p * 100) / production_p), 100) : 0;
```

Do you provide sensors for your essential and non-essential or do you let the card calculate this?

According to your screenshot 

```
production = 9635 + 0 + 0
consumption = 752 + nonessential + 0 + 0

Autarky = 752/9635 = 8%
Ratio = 9635/752 = 100%
```

**Comment by slipx06** [comment]
![autarky](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/23e6a779-f0a9-4a63-834f-03ee8591183c)

**Comment by slipx06** [comment]
@elRadix did you get this working?

**Comment by slipx06** [comment]
Assume this is working now so closing.
