### ISSUE TITLE
Translate "autarky"  in Italian

### ISSUE THREAD

**Issue by wifi75** [slipx06/sunsynk-power-flow-card#424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

in italian language autarky it it is not correctly translated

### Expected behaviour

translate as below:
Autosufficienza

### Possible Solutions

translate as below:
Autosufficienza

### Mode

lite

### Context / Reason

translate as below:
Autosufficienza

**Comment by slipx06** [comment]
This will cause the text to overlap with Ratio

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/69d88a11-42ea-47b2-b920-005c39dab7a1)

**Comment by slipx06** [comment]
Thanks I'll update the translation
