### ISSUE TITLE
Daily Grid Buy entity issue

### ISSUE THREAD

**Issue by amctear** [slipx06/sunsynk-power-flow-card#43]
Hi,

An odd one from yesterdays update.  It shows Zero grid import, yet selecting the entity shows the correct 18.6 imported  

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7934654/0540e931-5f8e-4b9e-b13a-ad15f45b1609)

**Comment by slipx06** [comment]
H
According to the screenshot the value of the grid_inport_day_buy sensor is 0.0kWh which is what the card is displaying.
