### ISSUE TITLE
Problem mapping to string.

### ISSUE THREAD

**Issue by ikeare** [slipx06/sunsynk-power-flow-card#434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Russian language has a problem with text and elements overlapping
![IMG_3966](https://github.com/slipx06/sunsynk-power-flow-card/assets/92827827/05479c0e-95d3-4820-afa8-8fbb1d292cb3)

### Steps To Reproduce

Constantly

### Expected behaviour

Words should be wrapped on another line, probably

### Card Version

4.37.0

### Home Assistant Version

12.3

**Comment by slipx06** [comment]
That's what happens when you use ChatGPT  😄 If you can help improve the translated text below I would be grateful 

```
{
    "common": {
        "description": "Карта Home Assistant для эмуляции потока энергии Sunsynk, отображаемого на экране инвертора",
        "version": "Версия",
        "runtime_to": "ВРЕМЯ ДО",
        "battery_floating": "ПЛАВАЮЩАЯ БАТАРЕЯ",
        "charge": "ЗАРЯД",
        "to": "ДО",
        "daily_load": "ЕЖЕДНЕВНАЯ НАГРУЗКА",
        "daily_aux": "ЕЖЕДНЕВНАЯ ВСПОМОГАТЕЛЬНАЯ",
        "daily_grid_buy": "ЕЖЕДНЕВНАЯ ПОКУПКА ИЗ СЕТИ",
        "daily_grid_sell": "ЕЖЕДНЕВНАЯ ПРОДАЖА В СЕТЬ",
        "daily_solar": "ЕЖЕДНЕВНАЯ СОЛНЕЧНАЯ ЭНЕРГИЯ",
        "daily_solar_left": "ЕЖЕДНЕВНАЯ СОЛНЕЧНАЯ ЭНЕРГИЯ / ОСТАЛОСЬ СЕГОДНЯ",
        "total_solar_generation": "ЕЖЕДНЕВНАЯ СОЛНЕЧНАЯ ЭНЕРГИЯ / TOTAL SOLAR",
        "daily_charge": "ЕЖЕДНЕВНАЯ ЗАРЯДКА",
        "daily_discharge": "ЕЖЕДНЕВНАЯ РАЗРЯДКА",
        "ratio": "Соотношение",
        "timer_off": "Таймер выключен",
        "timer_on": "Таймер включен",
        "priority_batt": "Приоритет батареи",
        "priority_load": "Приоритет нагрузки",
        "nonessential_name": "Не существенное",
        "aux_name": "Вспомогательное",
        "pv1_name": "PV1",
        "pv2_name": "PV2",
        "pv3_name": "PV3",
        "pv4_name": "PV4",
        "essential": "Существенное",
        "autarky": "Autarky",
        "discharging": "Разряд",
        "charging": "Зарядка",
        "waiting": "Ожидание",
        "standby": "Режим ожидания",
        "no_battery": "Без батареи",
        "selftest": "Самодиагностика",
        "normal": "Нормально",
        "alarm": "Авария",
        "fault": "Неисправность",
        "days": "дни",
        "hrs": "часов",
        "min": "мин",
        "flash": "Flash",
        "check": "Check",
        "idle": "Бездействие",
        "exporting": "Экспорт",
        "importing": "Импорт",
        "ongrid": "On-Grid",
        "offgrid": "Off-Grid",
        "normalstop": " Normal Stop",
        "shutdown": "Shutdown",
        "offline": "Offline",
        "running": "Running",
        "sleepmode": "Sleep Mode",
        "grid_name": "Grid",
        "limit": "Limit"
    },
    "errors": {
        "battery": {
            "bat": "Не определены атрибуты батареи",
            "energy": "Пожалуйста, включите атрибут батарейной энергии и значение в Втч, например, 5.32 Энергия батареи: 5320",
            "shutdown_soc": "Пожалуйста, включите атрибут батарейного shutdown_soc и значение, например, shutdown_soc: 20",
            "full_capacity": "Полная емкость должна быть в диапазоне от 80 до 100",
            "empty_capacity": "Пустая емкость должна быть <= 40",
            "show_daily": "Пожалуйста, включите атрибуты day_battery_charge_70 и day_battery_discharge_71 и идентификаторы сущностей"
        },
        "solar": {
            "sol": "Не определены атрибуты солнечной энергии",
            "mppts": "Пожалуйста, включите атрибут солнечных mppts и значение; 1,2,3 или 4, например, mppts: 2",
            "show_daily": "Пожалуйста, включите атрибут day_pv_energy_108 и идентификатор сущности"
        },
        "grid": {
            "show_daily": "Пожалуйста, включите атрибуты day_grid_import_76 и day_grid_export_77 и идентификаторы сущностей"
        },
        "essential_power": "Атрибут essential_power установлен на 'none'. Пожалуйста, включите атрибут inverter_power_175 и идентификатор сущности, чтобы карта могла вычислить это значение.",
        "nonessential_power": "Атрибут nonessential_power установлен на 'none'. Пожалуйста, включите атрибут grid_power_169 и идентификатор сущности, чтобы карта могла вычислить это значение.",
        "missing_entity": "Пожалуйста, включите атрибут и идентификатор сущности"
    },
    "config": {
      "title": "Title",
      "title_colour": "Title Colour",
      "title_size": "Title Size (px)",
      "card_height": "Card Height (px)",
      "card_width": "Card Width (px)",
      "decimal_places": "Decimal Places",
      "decimal_places_energy": "Decimal Places (Daily Energy)",
      "model": "Model",
      "autarky": "Autarky",
      "cardstyle": "Card Style",
      "large_font": "Large Font",
      "modern": "Modern",
      "show_solar": "Show Solar",
      "show_battery": "Show Battery",
      "show_grid": "Show Grid",
      "show_aux": "Show Aux",
      "dynamic_line_width": "Dynamic Line Width",
      "max_line_width": "Max Line Width",
      "min_line_width": "Min Line Width",
      "solar": "Solar",
      "mppts": "MPPTs",
      "show_daily": "Show Daily",
      "show_daily_aux": "Show Daily Aux",
      "animation_speed": "Anim. Speed",
      "max_power": "Max Power",
      "pv1_max_power": "PV1 Max Power",
      "pv2_max_power": "PV2 Max Power",
      "pv3_max_power": "PV3 Max Power",
      "pv4_max_power": "PV4 Max Power",
      "pv1_name": "PV1 Name",
      "pv2_name": "PV2 Name",
      "pv3_name": "PV3 Name",
      "pv4_name": "PV4 Name",
      "display_mode": "Display Mode",
      "efficiency": "Efficiency Mode",
      "battery": "Battery",
      "load1_name": "Load 1 Name",
      "load2_name": "Load 2 Name",
      "load3_name": "Load 3 Name",
      "load4_name": "Load 4 Name",
      "load1_icon": "Load 1 Icon",
      "load2_icon": "Load 2 Icon",
      "load3_icon": "Load 3 Icon",
      "load4_icon": "Load 4 Icon",
      "aux_load1_name": "Load 1 Name",
      "aux_load2_name": "Load 2 Name",
      "aux_load1_icon": "Load 1 Icon",
      "aux_load2_icon": "Load 2 Icon",
      "aux_dynamic_colour": "Aux Dynamic Colour",
      "show_daily_buy": "Show Daily Buy",
      "show_daily_sell": "Show Daily Sell",
      "no_grid_colour": "No Grid Colour",
      "grid_off_colour": "Grid Off Colour",
      "grid_name": "Grid Name",
      "colour": "Colour",
      "charge_colour": "Charge Colour",
      "linear_gradient": "Linear Gradient",
      "animate": "Animate Linear Gradient",
      "aux_colour": "Colour",
      "aux_off_colour": "Off Colour",
      "panel_mode": "Panel Mode",
      "invert_grid": "Invert Values",
      "invert_load": "Invert Values",
      "shutdown_soc": "Shutdown SOC",
      "energy": "Energy",
      "auto_scale": "Auto Scale",
      "three_phase": "Three Phase",
      "dynamic_colour": "Dynamic Colour",
      "dynamic_icon": "Dynamic Icon",
      "invert_power": "Invert Power",
      "show_absolute": "Show Absolute",
      "hide_soc": "Hide SOC",
      "invert_aux": "Invert Aux",
      "show_absolute_aux": "Show Absolute",
      "show_nonessential": "Show Non Essential",
      "aux_name": "Aux Name",
      "aux_daily_name": "Daily Aux Name",
      "aux_type": "Aux Icon",
      "aux_loads": "Aux Loads",
      "essential_name": "Essential Name",
      "additional_loads": "Additional Loads",
      "export_colour": "Export Colour",
      "nonessential_name": "Non Essential Name",
      "nonessential_icon": "Non Essential Icon",
      "energy_cost_decimals": "Energy Cost Decimals",
      "show_remaining_energy": "Show Remaining Energy",
      "cat_title": {
        "title": "Title Options",
        "general": "General Options",
        "inverter": "Inverter Options",
        "solar": "Solar Options",
        "battery": "Battery Options",
        "grid": "Grid Options",
        "load": "Load Options",
        "entities": "Entities",
        "aux": "Aux Options",
        "energy": "Energy Entities",
        "bat": "Battery Entities",
        "sol": "Solar Entities",
        "inv": "Inverter Entities",
        "ld": "Load Entities",
        "gri": "Grid Entities"
      }
    }
}
```

**Comment by ikeare** [comment]
> That's what happens when you use ChatGPT 😄 If you can help improve the translated text below I would be grateful
> 
> ```
> {
>     "common": {
>         "description": "Карта Home Assistant для эмуляции потока энергии Sunsynk, отображаемого на экране инвертора",
>         "version": "Версия",
>         "runtime_to": "ВРЕМЯ ДО",
>         "battery_floating": "ПЛАВАЮЩАЯ БАТАРЕЯ",
>         "charge": "ЗАРЯД",
>         "to": "ДО",
>         "daily_load": "НАГРУЗКА",
>         "daily_aux": "ВСПОМОГАТЕЛЬНАЯ",
>         "daily_grid_buy": "ПОКУПКА ИЗ СЕТИ",
>         "daily_grid_sell": "ПРОДАЖА В СЕТЬ",
>         "daily_solar": "ЕЖЕДНЕВНАЯ СОЛНЕЧНАЯ ЭНЕРГИЯ",
>         "daily_solar_left": "СОЛНЕЧНАЯ ЭНЕРГИЯ / ОСТАЛОСЬ СЕГОДНЯ",
>         "total_solar_generation": "СОЛНЕЧНАЯ ЭНЕРГИЯ / ИТОГО СОЛНЕЧНАЯ ЭНЕРГИЯ",
>         "daily_charge": "ЗАРЯД",
>         "daily_discharge": "РАЗРЯД",
>         "ratio": "Соотношение",
>         "timer_off": "Таймер выключен",
>         "timer_on": "Таймер включен",
>         "priority_batt": "Приоритет батареи",
>         "priority_load": "Приоритет нагрузки",
>         "nonessential_name": "Не существенное",
>         "aux_name": "Вспомогательное",
>         "pv1_name": "PV1",
>         "pv2_name": "PV2",
>         "pv3_name": "PV3",
>         "pv4_name": "PV4",
>         "essential": "Существенное",
>         "autarky": "Autarky",
>         "discharging": "Разряд",
>         "charging": "Заряд",
>         "waiting": "Ожидание",
>         "standby": "Режим ожидания",
>         "no_battery": "Без батареи",
>         "selftest": "Самодиагностика",
>         "normal": "Нормально",
>         "alarm": "Авария",
>         "fault": "Неисправность",
>         "days": "дни",
>         "hrs": "часов",
>         "min": "мин",
>         "flash": "Flash",
>         "check": "Check",
>         "idle": "Бездействие",
>         "exporting": "Экспорт",
>         "importing": "Импорт",
>         "ongrid": "On-Grid",
>         "offgrid": "Off-Grid",
>         "normalstop": "Остановка",
>         "shutdown": "Отключение",
>         "offline": "Оффлайн",
>         "running": "Работает",
>         "sleepmode": "Спящий Режим",
>         "grid_name": "Сеть",
>         "limit": "Лимит"
>     },
>     "errors": {
>         "battery": {
>             "bat": "Не определены атрибуты батареи",
>             "energy": "Пожалуйста, включите атрибут батарейной энергии и значение в Втч, например, 5.32 Энергия батареи: 5320",
>             "shutdown_soc": "Пожалуйста, включите атрибут батарейного shutdown_soc и значение, например, shutdown_soc: 20",
>             "full_capacity": "Полная емкость должна быть в диапазоне от 80 до 100",
>             "empty_capacity": "Пустая емкость должна быть <= 40",
>             "show_daily": "Пожалуйста, включите атрибуты day_battery_charge_70 и day_battery_discharge_71 и идентификаторы сущностей"
>         },
>         "solar": {
>             "sol": "Не определены атрибуты солнечной энергии",
>             "mppts": "Пожалуйста, включите атрибут солнечных mppts и значение; 1,2,3 или 4, например, mppts: 2",
>             "show_daily": "Пожалуйста, включите атрибут day_pv_energy_108 и идентификатор сущности"
>         },
>         "grid": {
>             "show_daily": "Пожалуйста, включите атрибуты day_grid_import_76 и day_grid_export_77 и идентификаторы сущностей"
>         },
>         "essential_power": "Атрибут essential_power установлен на 'none'. Пожалуйста, включите атрибут inverter_power_175 и идентификатор сущности, чтобы карта могла вычислить это значение.",
>         "nonessential_power": "Атрибут nonessential_power установлен на 'none'. Пожалуйста, включите атрибут grid_power_169 и идентификатор сущности, чтобы карта могла вычислить это значение.",
>         "missing_entity": "Пожалуйста, включите атрибут и идентификатор сущности"
>     },
>     "config": {
>       "title": "Заголовок",
>       "title_colour": "Цвет Заголовка",
>       "title_size": "Размер Заголовка (px)",
>       "card_height": "Высота Карточки (px)",
>       "card_width": "Ширина Карточки (px)",
>       "decimal_places": "Десятичные Знаки",
>       "decimal_places_energy": "Десятичные Знаки (Ежедневная Енергия)",
>       "model": "Модель",
>       "autarky": "Autarky",
>       "cardstyle": "Стиль Карточки",
>       "large_font": "Увеличенный Шрифт",
>       "modern": "Современный Инвертор",
>       "show_solar": "Показать PV",
>       "show_battery": "Показать Батарею",
>       "show_grid": "Показать Сеть",
>       "show_aux": "Показать Вспомогательный",
>       "dynamic_line_width": "Динамические линии",
>       "max_line_width": "Макс. Ширина Линий",
>       "min_line_width": "Мин. Ширина Линий",
>       "solar": "Solar",
>       "mppts": "MPPTs",
>       "show_daily": "Ежедневный Показатель",
>       "show_daily_aux": "Ежедневный показатель вспомогательный",
>       "animation_speed": "Скорость Анимации",
>       "max_power": "Макс. Мощность",
>       "pv1_max_power": "PV1 Макс. Мощность",
>       "pv2_max_power": "PV2 Макс. Мощность",
>       "pv3_max_power": "PV3 Макс. Мощность",
>       "pv4_max_power": "PV4 Макс. Мощность",
>       "pv1_name": "PV1 Название",
>       "pv2_name": "PV2 Название",
>       "pv3_name": "PV3 Название",
>       "pv4_name": "PV4 Название",
>       "display_mode": "Режим Отображения",
>       "efficiency": "Режим Эффективности",
>       "battery": "Батарея",
>       "load1_name": "Нагрузка 1 Название",
>       "load2_name": "Нагрузка 2 Название",
>       "load3_name": "Нагрузка 3 Название",
>       "load4_name": "Нагрузка 4 Название",
>       "load1_icon": "Нагрузка 1 Иконка",
>       "load2_icon": "Нагрузка 2 Иконка",
>       "load3_icon": "Нагрузка 3 Иконка",
>       "load4_icon": "Нагрузка 4 Иконка",
>       "aux_load1_name": "Вспом. Нагр. 1 Название",
>       "aux_load2_name": "Вспом. Нагр. 2 Название",
>       "aux_load1_icon": "Вспом. Нагр. 2 Иконка",
>       "aux_load2_icon": "Вспом. Нагр. 2 Иконка",
>       "aux_dynamic_colour": "Вспом. Нагр. Динамический Цвет",
>       "show_daily_buy": "Показать Ежедневную Покупку",
>       "show_daily_sell": "Показать Ежедневную Продажу",
>       "no_grid_colour": "Нет Сети Цвет",
>       "grid_off_colour": "Сеть Отключена Цвет",
>       "grid_name": "Название Сети",
>       "colour": "Цвет",
>       "charge_colour": "Цвет Зарядки",
>       "linear_gradient": "Градиент",
>       "animate": "Анимированный Градиент",
>       "aux_colour": "Цвет",
>       "aux_off_colour": "Цвет выключенного",
>       "panel_mode": "Panel Mode",
>       "invert_grid": "Инвертировать показания",
>       "invert_load": "Инвертировать показания",
>       "shutdown_soc": "% Отключения",
>       "energy": "Энергия",
>       "auto_scale": "Масштабирование",
>       "three_phase": "Три Фазы",
>       "dynamic_colour": "Динамический Цвет",
>       "dynamic_icon": "Динамическая Иконка",
>       "invert_power": "Инвертировать Мощность",
>       "show_absolute": "Убрать Отрицательные",
>       "hide_soc": "Скрыть SOC",
>       "invert_aux": "Инвертировать Вспомогательную",
>       "show_absolute_aux": "Убрать Отрицательные",
>       "show_nonessential": "Показать Не Обязательную Нагрузку",
>       "aux_name": "Название вспомогательного",
>       "aux_daily_name": "Название вспомогательного ежедневного",
>       "aux_type": "Тип вспомогательного",
>       "aux_loads": "Нагрузка вспомогательного",
>       "essential_name": "Название Обязательной Нагрузки",
>       "additional_loads": "Количество Нагрузок",
>       "export_colour": "Цвет Экспорта",
>       "nonessential_name": "Название Не Обязательной Нагрузки",
>       "nonessential_icon": "Иконка Не Обязательной Нагрузки",
>       "energy_cost_decimals": "Разрядность Стоимости Энергии",
>       "show_remaining_energy": "Показать Остаток Энергии",
>       "cat_title": {
>         "title": "Параметры Заголовка",
>         "general": "Общие Настройки",
>         "inverter": "Настройки Инвертора",
>         "solar": "Настройки Солнечного Поля",
>         "battery": "Настройки Батареи",
>         "grid": "Настройки Сети",
>         "load": "Настройки Нагрузки",
>         "entities": "Сущности",
>         "aux": "Настройки Всп. Нагрузки",
>         "energy": "Сущности Энергии",
>         "bat": "Сущности Батареи",
>         "sol": "Сущности Солнечного Поля",
>         "inv": "Сущности Инвертора",
>         "ld": "Сущности Нагрузки",
>         "gri": "Сущности Сети"
>       }
>     }
> }
> ```

How I see the card translation.
