### ISSUE TITLE
My batteries never reach 100%, but 99%. How to consider them as charged?

### ISSUE THREAD

**Issue by StefanoGiu** [slipx06/sunsynk-power-flow-card#442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My batteries never reach 100%, but 99%. How to consider them as charged?

### Expected behaviour

My batteries never reach 100%, but 99%. How to consider them as charged?

### Mode

full

### Context / Reason

My batteries never reach 100%, but 99%. How to consider them as charged?

**Comment by Pho3niX90** [comment]
@StefanoGiu this card just displays what it's being told. If your batteries never reach 100%, this would be your BMS not resetting, or cells not reaching the BMS set parameters to consider it full.
