### ISSUE TITLE
question: what is this SOC?

### ISSUE THREAD

**Issue by matomatusov** [slipx06/sunsynk-power-flow-card#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,
what is this SOC? I don't see it there and I don't know why.
![1](https://github.com/slipx06/sunsynk-power-flow-card/assets/129114957/d3ec640e-9ed1-4800-a136-0ab93088c14b)

Thanks

Edit:
I guess I figured it out.
Only works for Goodwe.
could I ask for an add for the SolaX model?
![2](https://github.com/slipx06/sunsynk-power-flow-card/assets/129114957/36ddad83-7a96-4397-a740-73ecc8c04adf)

Thanks

### Card Version

4.37.2

### Home Assistant Version

2024.5.4

**Comment by wacalitz** [comment]
Under Battery Options 
I believe it is the Shutdown SOC you've entered in the card
Lower down there is a toggle Hide SOC where you can toggle to show it or not.

Mine is set to off as I have markdown card giving me the relative SOC targets when charging and discharging.

**Comment by matomatusov** [comment]
@wacalitz 

That Hide SOC does nothing for me.
It's always the same.

**Comment by slipx06** [comment]
It displays the SOC setting (capacity) for the selected program mode/ timer mode. You need to provide a `use_timer_248:` sensor as well as program sensors below
```
  prog1_time: sensor.sunsynk_time_slot_1
  prog1_capacity: number.sunsynk_prog1_capacity
  prog1_charge: switch.sunsynk_prog1_grid_charge
  prog2_time: sensor.sunsynk_time_slot_2
  prog2_capacity: number.sunsynk_prog2_capacity
  prog2_charge: switch.sunsynk_prog2_grid_charge
  prog3_time: sensor.sunsynk_time_slot_3
  prog3_capacity: number.sunsynk_prog3_capacity
  prog3_charge: switch.sunsynk_prog3_grid_charge
  prog4_time: sensor.sunsynk_time_slot_4
  prog4_capacity: number.sunsynk_prog4_capacity
  prog4_charge: switch.sunsynk_prog4_grid_charge
  prog5_time: sensor.sunsynk_time_slot_5
  prog5_capacity: number.sunsynk_prog5_capacity
  prog5_charge: switch.sunsynk_prog5_grid_charge
  prog6_time: sensor.sunsynk_time_slot_6
  prog6_capacity: number.sunsynk_prog6_capacity
  prog6_charge: switch.sunsynk_prog6_grid_charge
```
Alternatively if the selected inverter is Goodwe or Huawei it will show the shutdown soc and the shutdown soc off_grid. 
Its not needed if you dont make use of the program mode as the shutdown soc is shown in the text

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/faa2c7c3-2366-4712-b4cd-8c76a2ed1b4d)
