### ISSUE TITLE
color the flow

### ISSUE THREAD

**Issue by jolly12f** [slipx06/sunsynk-power-flow-card#449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

at this moment the flow that goes from the inverter towards the house remains blue

### Expected behaviour

I would like to color the stream based on the source it is using

### Possible Solutions

It should take the color of the battery, the sun or the grid, so it would be nice to see the flow of the same color going towards the load. the house icon is already colored that way, I don't think there are any problems coloring the flow too

### Mode

Both

### Context / Reason

it would be more beautiful to look at

**Comment by jolly12f** [comment]
![IMG_3905](https://github.com/slipx06/sunsynk-power-flow-card/assets/124673918/59f3415e-b33c-4c4a-8b96-daa67c6b45d4)

**Comment by slipx06** [comment]
Hi. Something like this?

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/6e18a2db-0b87-4ca1-977e-c171579da2a2)

**Comment by Roving-Ronin** [comment]
@slipx06 dumb question... whats the 'Limit: 8.00 kW' map to ? 
I'm assuming it shows if there's a limit on the 'maximum export = xxxx W'?
Is this able to be linked to a sensor, as Huawei/iStore with WLCRS integration v1.4.0 (Alpha atm) adds:

- That sets the maximum export in Watts to the Grid:
 service: huawei_solar.set_maximum_feed_grid_power

- That sets the maximum export in % of overall inverter(s) capacity, to the Grid:
 service: huawei_solar.set_maximum_feed_grid_power_percentage   

- That allows resetting the maximum grid feed back to 100% of capabilities:
 service: huawei_solar.reset_maximum_feed_grid_power 

IIRC this is then sent to the inverters (or primary only that controls all of them?) at:
number.inverter_1_power_derating  or number.inverter_1_power_derating_by_percentage

**Comment by slipx06** [comment]
Yes maximum export to grid based on Watts. You can provide a sensor e.g. `max_sell_power: huawei_solar.set_maximum_feed_grid_power`

**Comment by jolly12f** [comment]
> CIAO. Qualcosa come questo?
> 
> ![Immagine](https://private-user-images.githubusercontent.com/7227275/333871793-6e18a2db-0b87-4ca1-977e-c171579da2a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MjgyNTksIm5iZiI6MTcxNjcyNzk1OSwicGF0aCI6Ii83MjI3Mjc1LzMzMzg3MTc5My02ZTE4YTJkYi0wYjg3LTRjYTEtOTc3ZS1jMTcxNTc5ZGEyYTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjZUMTI1MjM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjhhYjcwOTBhNzA5M2I0MmE0ZjdkNDQ1ZGM5MmNmZDczYmJhNzI4YWJiNDM2MjIwZTJhNGJmODBiNmUxY2Y5YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pBVrw8uQVjyRUzNZhaw6oKn2fApNTrEgAp2KEGiG-JI)

yes exactly, I would also color the tables with numbers!!

**Comment by slipx06** [comment]
I've only applied this to the path element for now and also implemented for the battery

**Comment by jolly12f** [comment]
> Per ora l'ho applicato solo all'elemento percorso e l'ho implementato anche per la batteria

I just updated but this doesn't happen
![IMG_3969](https://github.com/slipx06/sunsynk-power-flow-card/assets/124673918/a121ccaa-468e-448e-9e9b-b436cb5a29bb)

**Comment by Roving-Ronin** [comment]
@slipx06  thanks for this update. Could you please check your HA and see if you get this error also? I have the following sensors, like this (my own HA has a more complex tariff plan, but same format and issue):

```
    - name: "Electricity - Price" 
      unique_id: electricity_price
      unit_of_measurement: "$/kWh"
      device_class: monetary
      state: >
        {## Enter cost per kWh rates below. Rate 1 ##}
        {% set rate1 = 0.30812 %}
        {% set rate2 = 0.0 %}
        {% set power_meter_active_power = states('sensor.power_meter_active_power') | float %}
        {% if power_meter_active_power <= 0 %} {{rate1}}
        {% else %} {{rate2}}
        {% endif %}

#  Current FIT rate, rate 1 & 2 allows setting a second rate if variable FIT rates (i.e. $0.15 for first 10kWh, then $0.07 thereafter)

    - name: "Electricity - FIT"
      unique_id: electricity_fit
      unit_of_measurement: "$/kWh"
      device_class: monetary
      icon: mdi:cash-plus
      state: >
        {## Enter compensation per kWh rates below ##}
        {% set rate1 = 0.07 %}
        {% set rate2 = 0.07 %}
        {% set fit_exported_today = states('sensor.hs_grid_exported_daily') | float %}
        {% if fit_exported_today <= 10 %} {{rate1}}
        {% else %} {{rate2}}
        {% endif %}
```

These sensors output a Grid Export price (FIT) that when over 10kWh exported for the day reads as 0.07  (device_class: monetary so in the dash shows with the $), conversely the above it setup to say if the Power Meter is reading as <=0 Watts i.e. exporting, then report 0.30812

Given this when exporting the price showing next to the grid should be $0.07 $/kWh, however its showing as 0.07} $/kWh. 

...change of plans, I think I managed to find the typo myself. I've lodged PULL request if you want to check it please ?

https://github.com/slipx06/sunsynk-power-flow-card/pull/457

**Comment by Roving-Ronin** [comment]
@slipx06 just noticed this, now that I'm importing at night. Bit of overlap on the 'h' from kWh and the transmission tower.

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/108674933/716fe98d-e55c-4ad9-9d39-907acd02fa8f)

**Comment by slipx06** [comment]
> @slipx06 just noticed this, now that I'm importing at night. Bit of overlap on the 'h' from kWh and the transmission tower.
> 
> ![image](https://private-user-images.githubusercontent.com/108674933/334019464-716fe98d-e55c-4ad9-9d39-907acd02fa8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzU4ODAsIm5iZiI6MTcxNjgzNTU4MCwicGF0aCI6Ii8xMDg2NzQ5MzMvMzM0MDE5NDY0LTcxNmZlOThkLWU1NWMtNGFkOS05ZDM5LTkwN2FjZDAyZmE4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxODQ2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTNhZWM2MDdlY2U0OWY4YzUwNWI3NzhlMGExMWMwZThlNzc1MmI2YWQxNWFkZGI4MjA1ZmMyYzNmOTVhYzFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jKWhcvJeGAu8qX_LMgrOsNzhbpqA37ECy7UBIplB5HU)

Thanks I've corrected this

**Comment by github-daniel-stoian** [comment]
@slipx06 It's not working on my side. The load line is still blue.

- type: custom:sunsynk-power-flow-card
    cardstyle: compact
    panel_mode: true
    show_solar: true
    dynamic_line_width: false
    max_line_width: 8
    min_line_width: 2
    inverter:
      modern: false
      colour: '#1F618D'
      model: sofar
      autarky: 'no'
      three_phase: false
    battery:
      energy: 3500
      shutdown_soc: 20
      show_daily: false
      colour: '#47d147'
      max_power: 3500
      full_capacity: 100
      empty_capacity: 30
      dynamic_colour: true
      linear_gradient: true
    solar:
      show_daily: true
      mppts: 2
      colour: '#ffa31a'
      max_power: 6000
      pv1_name: PV1 Vest
      pv1_max_power: 4200
      pv2_name: PV2 Est
      pv2_max_power: 3500
      efficiency: 3
    load:
      show_daily: true
      dynamic_colour: true
      dynamic_icon: false
      colour: DeepSkyBlue
      max_power: 6000
      additional_loads: 4
      load1_name: Boiler
      load2_name: Heaters
      load3_name: DP1
      load4_name: DP2
      load1_icon: mdi:water-boiler
      load2_icon: mdi:heat-pump
      load3_icon: mdi:generator-portable
      load4_icon: mdi:generator-portable
    grid:
      show_daily_buy: true
      show_daily_sell: false
      show_nonessential: true
      max_power: 6000
      colour: '#ff0000'
<img width="1043" alt="Screenshot 2024-05-28 at 12 13 28" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/26714611/8b034692-dc67-4f47-9d89-1875b6a5340c">

**Comment by slipx06** [comment]
@github-daniel-stoian I think I found the issue. Can you enable dynamic Icon under load options and see if it enables this?

**Comment by github-daniel-stoian** [comment]
@slipx06 No, it does not work.
I've played extensivelly with dynamic_icon and dynamic_colour setting them true or false in any possible combination.

<img width="1527" alt="image" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/26714611/7bf26ca0-f3ad-405b-8293-f308585f14fe">

**Comment by slipx06** [comment]
No that's expected behavior. The colour of the line will only change when a single source is able to supply 100% of the load. Wait until you have enough PV and it will change. You have to have `dynamic_icon: true` but I'll fix that

**Comment by github-daniel-stoian** [comment]
It does not work when PV is able to supply 100% of the load.

But somehow it does work when Grid is providing 100% of the load.

<img width="1036" alt="image" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/26714611/d46499b7-4a56-4f0f-a38f-8b50b8bf72aa">

<img width="1045" alt="Screenshot 2024-05-28 at 13 51 19" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/26714611/b421f384-95e8-4c24-80b3-121b7d0c466c">

**Comment by slipx06** [comment]
Are you sure you have dynamic_icon is set to true in your first screenshot. The icon should show the picture of the house with solar panles and sun when the PV supply exceeds the load? In any case I need to update the code to remove the dependency on this setting. So wait for the next release to test.

**Comment by jolly12f** [comment]
in my case it doesn't color when 100% comes from the grid

**Comment by github-daniel-stoian** [comment]
Are you sure you have dynamic_icon is set to true in your first screenshot: Yes, I'm sure.
The icon should show the picture of the house with solar panles and sun when the PV supply exceeds the load? : No

<img width="1032" alt="Screenshot 2024-05-28 at 16 22 04" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/26714611/5a74b75d-74df-4081-b160-e2983fdd4fdd">

**Comment by slipx06** [comment]
Can you share your card config. Do you have a sensor defined for non essential power and aux power?

**Comment by github-daniel-stoian** [comment]
No sensors for non-essential and aux power.

- type: custom:sunsynk-power-flow-card
    cardstyle: compact
    panel_mode: true
    show_solar: true
    dynamic_line_width: false
    max_line_width: 8
    min_line_width: 2
    inverter:
      modern: false
      colour: '#1F618D'
      model: sofar
      autarky: 'no'
      three_phase: false
    battery:
      energy: 3500
      shutdown_soc: 20
      show_daily: false
      colour: '#47d147'
      max_power: 3500
      full_capacity: 100
      empty_capacity: 30
      dynamic_colour: true
      linear_gradient: true
    solar:
      show_daily: true
      mppts: 2
      colour: '#ffa31a'
      max_power: 6000
      pv1_name: PV1 Vest
      pv1_max_power: 4200
      pv2_name: PV2 Est
      pv2_max_power: 3500
      efficiency: 3
    load:
      show_daily: true
      dynamic_colour: true
      dynamic_icon: true
      colour: DeepSkyBlue
      max_power: 6000
      additional_loads: 4
      load1_name: Boiler
      load2_name: Heaters
      load3_name: DP1
      load4_name: DP2
      load1_icon: mdi:water-boiler
      load2_icon: mdi:heat-pump
      load3_icon: mdi:generator-portable
      load4_icon: mdi:generator-portable
    grid:
      show_daily_buy: true
      show_daily_sell: false
      show_nonessential: true
      max_power: 6000
      colour: '#ff0000'
    entities:
      battery_voltage_183: sensor.uyn2hxn009_battery_voltage
      battery_current_191: sensor.uyn2hxn009_battery_ac_charge_current
      battery_soc_184: sensor.uyn2hxn009_state_of_charge
      battery_power_190: sensor.uyn2hxn009_battery_power
      day_battery_charge_70: sensor.uyn2hxn009_battery_ac_charge_energy_today
      day_battery_discharge_71: sensor.uyn2hxn009_battery_discharged_energy_today
      grid_power_169: sensor.uyn2hxn009_ac_discharge_load_consumption_power
      grid_voltage: sensor.uyn2hxn009_grid_voltage
      day_grid_import_76: sensor.uyn2hxn009_ac_discharge_energy_ac_bypass_today
      grid_ct_power_172: sensor.grid_discharge_power
      day_load_energy_84: sensor.consumed
      day_pv_energy_108: sensor.uyn2hxn009_power_generation_today_pvenergytoday
      pv1_power_186: sensor.uyn2hxn009_pv1_power
      pv2_power_187: sensor.uyn2hxn009_pv2_power
      pv1_voltage_109: sensor.pv1_voltage
      inverter_current_164: sensor.uyn2hxn009_inverter_current
      inverter_voltage_154: sensor.uyn2hxn009_inverter_output_voltage
      pv2_voltage_111: sensor.pv2_voltage
      essential_load1: sensor.boiler_power
      essential_load2: sensor.heaters_consumption
      essential_load3: sensor.dp1_battery_level
      essential_load4: sensor.dp2_battery_level
      essential_load1_extra: sensor.dp1_solar_in_power
      essential_load2_extra: sensor.dp2_solar_in_power

**Comment by github-daniel-stoian** [comment]
Seems to work now after I've changed the followings:
```
    solar:
      off_threshold: 1
      
   load:
      off_threshold: 1
      path_threshold: 90
      
    grid:
      no_grid_colour: grey
      off_threshold: 1
      
     entities:
      grid_power_169 replaces with essential_power
```

<img width="1038" alt="image" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/26714611/87fcb94a-3565-4b2f-87a4-28c402f5b18e">
