### ISSUE TITLE
Back Button Android

### ISSUE THREAD

**Issue by floschad** [slipx06/sunsynk-power-flow-card#450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I push back button after I clicked a value to see details nothing happens, 2nd time App will close.

### Steps To Reproduce

Tap on a value in the card to open details, then back button.

### Expected behaviour

Normally when you push back button it will close the detail window in the App.

### Card Version

4.38.0

### Home Assistant Version

2024.5.5

**Comment by slipx06** [comment]
Thanks I can confirm this behavior.  Will try figure out how to fix.

**Comment by Pho3niX90** [comment]
It seems I cannot reproduce this, which android versions are you using, and which devices? @slipx06

**Comment by Pho3niX90** [comment]
After upgrading to 24.5.5, I experience the same. Will quickly test.

**Comment by slipx06** [comment]
Not just Android. I can replicate in Chrome on Windows.
