### ISSUE TITLE
wrong flow color

### ISSUE THREAD

**Issue by jolly12f** [slipx06/sunsynk-power-flow-card#458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

with the latest update the flow from inverter to load is colored but when the load is powered by two sources such as photovoltaic and battery the color of the flow remains neutral

### Steps To Reproduce

the load has two power sources

### Expected behaviour

the flow could be of two colors or have the color of the more powerful one

### Card Version

Lastest

### Home Assistant Version

Lastre

**Comment by jolly12f** [comment]
![IMG_3977](https://github.com/slipx06/sunsynk-power-flow-card/assets/124673918/5180b763-505c-4031-a3dc-59c6771d9fe6)

**Comment by slipx06** [comment]
Currently the colour of the path will only change if the load or battery is being supplied 100% by one source i.e. grid or solar. Where there is a combination of two sources it reverts to the colour defined in your config

**Comment by jolly12f** [comment]
Yes, I saw, could it be modified with the two colors or with the one that exceeds 50%?

**Comment by jolly12f** [comment]
I can't find where to change this parameter

**Comment by slipx06** [comment]
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/362e952e-62a9-42d4-92a1-0823b03da262)

Under load and battery

```
battery:
  path_threshold: 100
load:
  path_threshold: 100
```

**Comment by jolly12f** [comment]
![IMG_4028](https://github.com/slipx06/sunsynk-power-flow-card/assets/124673918/d311a9be-6c41-4d30-88fd-3aa6af38ae77)

**Comment by jolly12f** [comment]
Ok i have find

**Comment by jolly12f** [comment]
> ![image](https://private-user-images.githubusercontent.com/7227275/334938491-362e952e-62a9-42d4-92a1-0823b03da262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMTU5NTIsIm5iZiI6MTcxNzAxNTY1MiwicGF0aCI6Ii83MjI3Mjc1LzMzNDkzODQ5MS0zNjJlOTUyZS02MmE5LTQyZDQtOTJhMS0wODIzYjAzZGEyNjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMjA0NzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGRjNGM0ZGZhMTY4YzY0N2M3M2IzNjkzNDMwZWFiNTVjMGFlMzg3MzJjOTc5NjBjYzAyMWIzZWRmMjllMzk0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ut-2CGLCS9hfx77srb0vE-69jba89U30Mpt9eBIrNNg)
> 
> Under load and battery
> 
> ```
> battery:
>   path_threshold: 100
> load:
>   path_threshold: 100
> ```

the non-use range should be adjusted in the grid, not just a minimum threshold because when the energy is introduced the value is always negative even if it is a value close to 0 it is not to be considered
