### ISSUE TITLE
Load 1 and 2 icons

### ISSUE THREAD

**Issue by Gorwanvfr** [slipx06/sunsynk-power-flow-card#46]
Would it be possible to add the facility to add icons to load 1 and 2 on essential loads? The same as you have for nonessential loads.

**Comment by slipx06** [comment]
It's possible but I cant see how these would fit on the card given the limited space

**Comment by slipx06** [comment]
Added to v1.8.0

**Comment by wacalitz** [comment]
Thanks, can a stove icon be added as well in a future update.  
Also I notice the icons only show in the full layout not the lite.  Any possibility to add this to the lite layout 
Perhaps here:
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/124435236/5aa50169-bdfc-45de-9e26-25c00b847380)
Thanks

**Comment by slipx06** [comment]
Yes. I'll add it.  I didn't have time to work on the lite card. Will do that this weekend.

**Comment by slipx06** [comment]
Added to v1.8.1
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/56de1a13-a7b4-436e-82da-da59caa4e385)

**Comment by slipx06** [comment]
You can now use mdi icons in 1.8.2 😄 

![mdi-icons](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/c47abd93-cc65-45a9-b4d4-1c36f06f4c7c)

**Comment by Gorwanvfr** [comment]
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/132362732/1a8ed9a4-5fc4-4d4b-95e6-9494246203c6)

**Comment by Gorwanvfr** [comment]
One small issue with the mdi icons. When the card is in panel mode the mdi icons are in the middle of the card. 
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/132362732/83a62da0-f8c7-4545-ac2a-7172d0d9fce1)

When the card is not in panel mode then the icons are offset to the left. 
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/132362732/686a3126-4b48-4741-b15c-694d2cf3d053)

**Comment by slipx06** [comment]
That's strange, I cant reproduce that.  Does it happen on all your devices? What browser are you using?

**Comment by slipx06** [comment]
Seems to be a known issue with Safari.

**Comment by Gorwanvfr** [comment]
Fixed positions looks to be working. 
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/132362732/3cb5a51d-3f9e-44cf-86d5-d3515f8591f1)
