### ISSUE TITLE
SOH

### ISSUE THREAD

**Issue by kisjeth** [slipx06/sunsynk-power-flow-card#460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I consider the card extremely valid and with possible further implementations

### Expected behaviour

Would it be possible to also include the SOH in the battery section?

### Mode

full

### Context / Reason

For owners of storage batteries, this would be important data that they can always have under control.

**Comment by slipx06** [comment]
Thanks but where would you want to display that?

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/a9607eee-ff33-407e-9cc1-b8b256c9ce66)

**Comment by kisjeth** [comment]
Yes, where you marked, or above, although I realize that each configuration can vary and so your choice may be the best. Alternatively you could opt to choose which parameter to display between the SOC shutdown or the SOH

![IMG_20240601_111929](https://github.com/slipx06/sunsynk-power-flow-card/assets/91030699/4bc04706-58fd-44ec-8048-1779c5b7b520)

**Comment by slipx06** [comment]
That space is currently used to show battery temperature. Will see what I can do

**Comment by slipx06** [comment]
Added but please note you can chose to display either battery temperature or battery SOH but not both. They are displayed in the same place on the card. If battery_temp_182: is defined it will take priority and this sensor will not be displayed.
