### ISSUE TITLE
Allow specifying thresholds for dynamic colour

### ISSUE THREAD

**Issue by chickenbeef** [slipx06/sunsynk-power-flow-card#462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With dynamic colour, the off value is hardcoded to `0` to indicate an `off` state.

### Expected behaviour

I'd like to be able to configure the colour based on the load. I checked the docs but couldn't see anything for this currently being supported hence the feature request.

Example:

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/11455025/3dabcb0d-28e4-4cda-863c-f7cfddb3b63a)

In this image my Oven is always coloured as being `On` because it has a clock (and a gas igniter for the stove) that draws 1-8W when the oven is off.
Same for the D/Wash that has a parasitic draw of 2W when it's off.

It would be nice to be able to configure thresholds so that when the draw for these devices are < `configured threshold` it gets coloured as being off. That way I can see if items are on from a quick glance.

### Mode

full

### Context / Reason

This feature could later evolve to colouring the states based on the level of load.

**Comment by jolly12f** [comment]
I find this very correct. I have this problem of micro withdrawals from the grid which are very annoying

**Comment by Roving-Ronin** [comment]
@chickenbeef 
Out of interest what are you using to get these active power readings for the oven / gas etc?

**Comment by chickenbeef** [comment]
> @chickenbeef Out of interest what are you using to get these active power readings for the oven / gas etc?

The oven is on the Aux output of the inverter. Other devices are on multiple different plugs (Sonoff, Shelly, Tuya)

**Comment by jolly12f** [comment]
I can't find where to change this parameter
