### ISSUE TITLE
the threshold doesn't work

### ISSUE THREAD

**Issue by jolly12f** [slipx06/sunsynk-power-flow-card#465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

if I set the threshold to 50 the flow should be gray when it goes below that number but it doesn't work

### Expected behaviour

the function should work in a set range from negative to positive. because when the energy is fed into the grid I have a negative value but this too must not be considered below a threshold

![IMG_4029](https://github.com/slipx06/sunsynk-power-flow-card/assets/124673918/b370bcd5-69eb-4cb9-8135-0f05f85dda45)

### Card Version

Lastet

### Home Assistant Version

Lastrate

**Comment by slipx06** [comment]
Hi. I haven't applied the threshold to the grid yet. It only applies to the non_essential and essential and PV loads. I will consider adding it into the next release if no issues.
