### ISSUE TITLE
Add the direction of the energy flow from the grid

### ISSUE THREAD

**Issue by matomatusov** [slipx06/sunsynk-power-flow-card#469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the power is taken from the grid, the direction is not displayed.
If I send power to the grid, the direction is displayed.

### Expected behaviour

Would it be possible to add the direction of the energy flow from the grid?
![1](https://github.com/slipx06/sunsynk-power-flow-card/assets/129114957/8ed20aaa-1887-4b11-b185-44e8a0db1d62)

### Card Version

4.40.1

### Home Assistant Version

2024.5.4

**Comment by slipx06** [comment]
I guess the assumption was that most people don't feed back to the grid so the normal grid icon would be sufficient.

**Comment by matomatusov** [comment]
If there is no solar or battery power, the icon could show that the direction is from the grid.
The current grid icon can also remain.

**Comment by slipx06** [comment]
In the latest [release](https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v4.42.0) you can achieve this by adding this to your config:

```
grid:
  import_icon: mdi:transmission-tower-export
```
