### ISSUE TITLE
Compact Mode / Display essential_load1_extra, essential_load2_extra, essential_load3_extra, essential_load4_extra 

### ISSUE THREAD

**Issue by MiniBlister** [slipx06/sunsynk-power-flow-card#472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the compact mode the essential_load1_extra, essential_load2_extra, essential_load3_extra, essential_load4_extra is not shown

![grafik](https://github.com/slipx06/sunsynk-power-flow-card/assets/19893470/47f5a107-9660-4140-be9d-656ab949186b)

### Expected behaviour

It seems like there is space to show the values. 

### Possible Solutions

In case Load1 and Load2 would be moved up by 20 the extra field could be displayed as well.

![grafik](https://github.com/slipx06/sunsynk-power-flow-card/assets/19893470/4f2150a3-c6d9-4c16-bc3d-924dec4fc939)

### Mode

lite

### Context / Reason

add additional space between. 20 px should be enough and display the extra fields

**Comment by MiniBlister** [comment]
Ahh, just realized, that extra3 and extra4 do not exist yet

**Comment by slipx06** [comment]
At the moment extra information is only displayed when you have 2 loads. I never added them because of space but I can relook at it.

**Comment by MiniBlister** [comment]
I added load3 and load4 in local copy but still need to work the position. Do you want me to commit the change in case done?

**Comment by slipx06** [comment]
Sure. Happy for you to submit a pull request

**Comment by MiniBlister** [comment]
submitted a pull request. Hope this works. Please let me know in case I did something wrong
