### ISSUE TITLE
animate a line

### ISSUE THREAD

**Issue by jolly12f** [slipx06/sunsynk-power-flow-card#474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

at this moment the line above the inverter remains static and one color

### Expected behaviour

it could move and color like other flows

### Possible Solutions

Is it possible to color it with the flow of use like that little piece that goes towards the grid?

### Mode

full

### Context / Reason

improve visualization
![IMG_4107](https://github.com/slipx06/sunsynk-power-flow-card/assets/124673918/99b68809-5f6a-4d46-ad24-71154ce9d116)

**Comment by slipx06** [comment]
Sure, let me see what I can do

**Comment by jolly12f** [comment]
Great!
