### ISSUE TITLE
Generator alternative to Grid

### ISSUE THREAD

**Issue by tiaanv** [slipx06/sunsynk-power-flow-card#475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Card does not cater for generator input

### Expected behaviour

My system is completely off-grid.    Instead, I have a generator connected to my inverters.  Would be great to be able to either add generator support, or simply for now make the Grid options cater for a different icon on the grid side.

### Possible Solutions

Changeable Grid Icon.
Separate settings for Generator input.

### Mode

Both

### Context / Reason

This is probably only applicable to a very small subset of people, so not expecting too much effort/support for this.  I could fork, and dive into this myself, but then it becomes a pain to maintain, if this does gain some favour, I am happy to do some potential dev as a starting point for a PR.

**Comment by slipx06** [comment]
Hi. The card does support generator input. You should use the aux input.

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/d322c682-1aa0-422b-8208-d2bd56eeed26)

**Comment by tiaanv** [comment]
Thx, for the feedback.  
Yes, I know.  
I really did not state my requirement well enough.

I prefer the "Lite" option for an overview, and in that mode the AUX is not shown.  Grid however is.

Interestingly, I have come across an off-grid install, where the Grid input was used for the Generator, and the AUX/GEN input was used in smartload config.

I still appreciate, that this could be a silly requirement, but all it really boils down to, is being able to change the icon of the Grid.

**Comment by slipx06** [comment]
Hi. Ok I understand the request. I'll take a look.

**Comment by slipx06** [comment]
@tiaanv Added to the latest release.  Please test

```
grid:
  import_icon: mdi:generator-mobile
  export_icon: mdi:generator-mobile
  disconnected_icon: mdi:generator-mobile
```

**Comment by tiaanv** [comment]
I updated, it worked.  Could even set the icons from the frontend,  but then for some reason today, even though I have the yaml in there, it does not work, and the front-end options are reverted to the old one...  Not sure if this has to do with HA updating...

Either way, It did work, and perfectly addressed my requirement.  I really appreciate the change...  Wanted to post some screenshots, but now it doesn't work.  Will fiddle and report back when I can.

As a side note, but I could log another issue for that separately, the NAME is static, so when I enable Daily Import, it would say "Daily Grid Buy".  Ideally this should use the NAME as provided in the Grid name?

**Comment by slipx06** [comment]
Ok thanks for the feedback. It might be a caching issue. Not sure. Try clear your browser cache or incognito mode.  Might be better to just change that to "Daily Import" and "Daily Export"

**Comment by tiaanv** [comment]
Got to be a caching issue. the "Daily Import" option is perfect.

**Comment by slipx06** [comment]
@tiaanv You can set custom labels in https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v4.43.0

**Comment by tiaanv** [comment]
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/4703398/e8fa9201-048c-457d-ac09-9222a63e99da)
Everything 100% I hoped for.  Thank you!!! Enjoy the coffee! ;)

**Comment by slipx06** [comment]
Thanks for the coffee 😄
