### ISSUE TITLE
Off Grid Icon

### ISSUE THREAD

**Issue by bazcurtis** [slipx06/sunsynk-power-flow-card#478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It shares the export_icon: mdi:transmission-tower-export icon

### Expected behaviour

I would like it to use mdi:transmission-tower-off

### Possible Solutions

Add an off_grid_icon option. I thought the disconnected_icon would provide this option

### Mode

Both

### Context / Reason

I think that would cover all options.

**Comment by slipx06** [comment]
Hi. That icon will only display when your grid power = 0 and and the grid_connected_status_194: is reporting the correct grid disconnected state

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/b103fe8a-4d60-4134-9a85-1aec5912d5f1)

**Comment by bazcurtis** [comment]
Thanks, I will look into that. I have a binary sensor that I made already. I assume 0 watts was enough. I did not have 194 in my config.

**Comment by slipx06** [comment]
The reason it's needed because you can still have your grid connected but you are just not drawing any power.

**Comment by bazcurtis** [comment]
It is working fine now. Thanks for the help.
