### ISSUE TITLE
New Names

### ISSUE THREAD

**Issue by Garreth2013** [slipx06/sunsynk-power-flow-card#49]
Not all new names are working in the new release. Some of the names work in safari some dont in Chrome

**Comment by slipx06** [comment]
Hi. Did you update from an older version of the card? If so it could be a caching issue. 
I have not noticed any issued with Chrome. Perhaps you can provide some more detail?

**Comment by Garreth2013** [comment]
Had to clear Safari cache. All good now. Thanks for the great card
