### ISSUE TITLE
Improve card with power values

### ISSUE THREAD

**Issue by basti122303** [slipx06/sunsynk-power-flow-card#499]
### Current Behavior

Click on power values does nothing.

### Expected behaviour

![example](https://github.com/user-attachments/assets/d26f7f04-c46e-4884-a47e-a0d289b43ec3)

### Mode

Both

**Comment by slipx06** [comment]
Hi. Both of those values can be clicked to bring up more info. What sensors are you using for:

essential_power:
grid_ct_power_172:
