### ISSUE TITLE
[FEATURE REQUEST] Clickable Total Solar entity

### ISSUE THREAD

**Issue by NemesisXB** [slipx06/sunsynk-power-flow-card#51]
It would be great if the total solar entity is clickable. If a user does not have a combined entity the automatic calculation can be used. Maybe a user can select "auto" as the "entity" for automatic calculation (which will then not be clickable)
For example if you have a combined entity: combined_solar_power: sensor.deye_combined_solar
and if a user does not have a combined entity: combined_solar_power: auto
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/485436/95a14c92-4d53-48b1-bf5a-df1a60c2c6fd)

**Comment by Quintinvw** [comment]
That would be a great addition.

**Comment by slipx06** [comment]
Good idea. Added to v1.9.4

**Comment by NemesisXB** [comment]
Wow. That was Quick. Seems to work great. Thanks
