### ISSUE TITLE
Strange corruption on macOS Safari

### ISSUE THREAD

**Issue by quentinsf** [slipx06/sunsynk-power-flow-card#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Anybody seen strange corruption like this on Safari?

<img width="509" alt="Screenshot 2024-09-14 at 18 59 11" src="https://github.com/user-attachments/assets/14dbf2dc-5c70-466d-a9b8-07c3a406608f">

It seems to be a problem parsing some of the SVG - I'm getting console errors like:

`Error: Invalid value for <svg> attribute y="t=>xn.handlePopup(t,e.entities.grid_connected_status_194)"`

It works fine on other browsers on the same machine, and in the HA app, and in Safari on my iOS devices.

However, I *do* see the same thing on two different Macs, running slightly different versions of Safari and very different versions of macOS. So it's not just my one individual machine, and I've tried flushing caches, reloading resources etc.

This started when I updated Home Assistant to 2024.9.1 and the Sunsynk card to v4.44.0 at the same time, so I'm afraid I can't tell which was responsible.  My guess is that the SVG parser on macOS Safari may be fussier than some others, and there's a closed quote missing or something.

It may, of course, be something about my config, so I'm curious to know if others are running the latest version successfully on macOS Safari?

### Steps To Reproduce

e.g. in Safari 16.6 on macOS Ventura, load a page with the Sunsynk card

### Expected behaviour

I've been seeing a lovely card up until this latest update.

### Card Version

v4.44.0

### Home Assistant Version

2024.9.1

### Relevant log output

```shell
[Error] Error: Invalid value for <svg> attribute y="t=>xn.handlePopup(t,e.entities.grid_connected_status_194)"
	j (sunsynk-power-flow-card.js:24:5992)
	_$AI (sunsynk-power-flow-card.js:24:5911)
	p (sunsynk-power-flow-card.js:24:3620)
	$ (sunsynk-power-flow-card.js:24:4679)
	_$AI (sunsynk-power-flow-card.js:24:4176)
	(anonymous function) (app.wNoxo8Q30IA.js:2:352642)
	(anonymous function) (sunsynk-power-flow-card.js:30:512)
	update (sunsynk-power-flow-card.js:30:519)
	performUpdate (sunsynk-power-flow-card.js:12:5142)
	(anonymous function) (sunsynk-power-flow-card.js:12:4594)
[Error] Error: Problem parsing d="3.37875"
	j (sunsynk-power-flow-card.js:24:5992)
	_$AI (sunsynk-power-flow-card.js:24:5911)
	p (sunsynk-power-flow-card.js:24:3620)
	$ (sunsynk-power-flow-card.js:24:4679)
	_$AI (sunsynk-power-flow-card.js:24:4176)
	(anonymous function) (app.wNoxo8Q30IA.js:2:352642)
	(anonymous function) (sunsynk-power-flow-card.js:30:512)
	update (sunsynk-power-flow-card.js:30:519)
	performUpdate (sunsynk-power-flow-card.js:12:5142)
	(anonymous function) (sunsynk-power-flow-card.js:12:4594)
[Error] Error: Invalid value for <svg> attribute y="t=>xn.handlePopup(t,e.entities.grid_connected_status_194)"
	j (sunsynk-power-flow-card.js:24:5992)
	_$AI (sunsynk-power-flow-card.js:24:5911)
	p (sunsynk-power-flow-card.js:24:3620)
	$ (sunsynk-power-flow-card.js:24:4679)
	_$AI (sunsynk-power-flow-card.js:24:4176)
	(anonymous function) (app.wNoxo8Q30IA.js:2:352642)
	(anonymous function) (sunsynk-power-flow-card.js:30:512)
	update (sunsynk-power-flow-card.js:30:519)
	performUpdate (sunsynk-power-flow-card.js:12:5142)
	(anonymous function) (sunsynk-power-flow-card.js:12:4594)
[Error] Error: Problem parsing d="96"
	j (sunsynk-power-flow-card.js:24:5992)
	_$AI (sunsynk-power-flow-card.js:24:5911)
	p (sunsynk-power-flow-card.js:24:3620)
	$ (sunsynk-power-flow-card.js:24:4679)
	_$AI (sunsynk-power-flow-card.js:24:4176)
	(anonymous function) (app.wNoxo8Q30IA.js:2:352642)
	(anonymous function) (sunsynk-power-flow-card.js:30:512)
	update (sunsynk-power-flow-card.js:30:519)
	performUpdate (sunsynk-power-flow-card.js:12:5142)
	(anonymous function) (sunsynk-power-flow-card.js:12:4594)
[Error] Error: Invalid value for <svg> attribute y="t=>xn.handlePopup(t,e.entities.grid_connected_status_194)"
	j (sunsynk-power-flow-card.js:24:5992)
	_$AI (sunsynk-power-flow-card.js:24:5911)
	p (sunsynk-power-flow-card.js:24:3620)
	$ (sunsynk-power-flow-card.js:24:4679)
	_$AI (sunsynk-power-flow-card.js:24:4176)
	(anonymous function) (app.wNoxo8Q30IA.js:2:352642)
	(anonymous function) (sunsynk-power-flow-card.js:30:512)
	update (sunsynk-power-flow-card.js:30:519)
	performUpdate (sunsynk-power-flow-card.js:12:5142)
	(anonymous function) (sunsynk-power-flow-card.js:12:4594)
[Error] Error: Problem parsing d="3.380625"
	j (sunsynk-power-flow-card.js:24:5992)
	_$AI (sunsynk-power-flow-card.js:24:5911)
	p (sunsynk-power-flow-card.js:24:3620)
	$ (sunsynk-power-flow-card.js:24:4679)
	_$AI (sunsynk-power-flow-card.js:24:4176)
	(anonymous function) (app.wNoxo8Q30IA.js:2:352642)
	(anonymous function) (sunsynk-power-flow-card.js:30:512)
	update (sunsynk-power-flow-card.js:30:519)
	performUpdate (sunsynk-power-flow-card.js:12:5142)
	(anonymous function) (sunsynk-power-flow-card.js:12:4594)
[Error] Error: Invalid value for <svg> attribute y="t=>xn.handlePopup(t,e.entities.grid_connected_status_194)"
	j (sunsynk-power-flow-card.js:24:5992)
	_$AI (sunsynk-power-flow-card.js:24:5911)
	p (sunsynk-power-flow-card.js:24:3620)
	$ (sunsynk-power-flow-card.js:24:4679)
	_$AI (sunsynk-power-flow-card.js:24:4176)
	(anonymous function) (app.wNoxo8Q30IA.js:2:352642)
	(anonymous function) (sunsynk-power-flow-card.js:30:512)
	update (sunsynk-power-flow-card.js:30:519)
	performUpdate (sunsynk-power-flow-card.js:12:5142)
	(anonymous function) (sunsynk-power-flow-card.js:12:4594)
[Error] Error: Problem parsing d="94"
	j (sunsynk-power-flow-card.js:24:5992)
	_$AI (sunsynk-power-flow-card.js:24:5911)
	p (sunsynk-power-flow-card.js:24:3620)
	$ (sunsynk-power-flow-card.js:24:4679)
	_$AI (sunsynk-power-flow-card.js:24:4176)
	(anonymous function) (app.wNoxo8Q30IA.js:2:352642)
	(anonymous function) (sunsynk-power-flow-card.js:30:512)
	update (sunsynk-power-flow-card.js:30:519)
	performUpdate (sunsynk-power-flow-card.js:12:5142)
	(anonymous function) (sunsynk-power-flow-card.js:12:4594)
[Error] Error: Invalid value for <svg> attribute y="t=>xn.handlePopup(t,e.entities.grid_connected_status_194)"
	j (sunsynk-power-flow-card.js:24:5992)
	_$AI (sunsynk-power-flow-card.js:24:5911)
	p (sunsynk-power-flow-card.js:24:3620)
	$ (sunsynk-power-flow-card.js:24:4679)
	_$AI (sunsynk-power-flow-card.js:24:4176)
	(anonymous function) (app.wNoxo8Q30IA.js:2:352642)
	(anonymous function) (sunsynk-power-flow-card.js:30:512)
	update (sunsynk-power-flow-card.js:30:519)
	performUpdate (sunsynk-power-flow-card.js:12:5142)
	(anonymous function) (sunsynk-power-flow-card.js:12:4594)
```

**Comment by itsgucci** [comment]
I am experiencing the same issue of the icons not showing up, but mine is running in the macos Home Assistant app and not through a browser. 
<img width="541" alt="Screenshot 2024-09-14 at 11 53 00 AM" src="https://github.com/user-attachments/assets/23a304b8-aa2e-42d3-8128-c2b02c710276">

It does work if I go into edit the cards, and select lite version. (I am using the full) until I quit and relaunch the app, then the lite will be corrupted, and I can select the full, which works until I quit the app. 
<img width="1112" alt="Screenshot 2024-09-14 at 11 56 59 AM" src="https://github.com/user-attachments/assets/f9b94f7a-eb87-4f6e-baf3-fb66ad2666c6">
<img width="1103" alt="Screenshot 2024-09-14 at 11 56 48 AM" src="https://github.com/user-attachments/assets/c160472b-9e2a-4cc2-9e41-cbbf5b210ecb">
<img width="1065" alt="Screenshot 2024-09-14 at 11 56 41 AM" src="https://github.com/user-attachments/assets/d55da163-8230-4bf3-a756-db90292041b9">

So it seems it is there when first selected, but after relaunching something fails.

<img width="259" alt="Screenshot 2024-09-14 at 12 00 54 PM" src="https://github.com/user-attachments/assets/b87beae4-799e-441c-81b5-e63c45917734">

macos sonoma 14.6.1
card v4.44.0

**Comment by slipx06** [comment]
Hi

Unfortunately a know issue with dynamic css and styles and what HA considers to be a legacy browser. See https://github.com/slipx06/sunsynk-power-flow-card/issues/500

You can revert back to 2024.7.4 or upgrade your device/browser

**Comment by quentinsf** [comment]
> Unfortunately a know issue with dynamic css and styles and what HA considers to be a legacy browser. See #500

Ah, but my Safari is the latest version and way newer than anything labelled ‘legacy’ there.

**Comment by pepe895** [comment]
Its not about system or browser. A have same problem at tablets with Android 11 + 12 and new browser. I also have old phone with Android 9 where card working without problem.

**Comment by purewhitedesign** [comment]
Same here. A few days ago it looks like the posted screenshots above. But only on the iPad Air 4th. On PC and iPhone it works flawless!

iPhone:
![33](https://github.com/user-attachments/assets/a9fff605-a0ad-402d-9d39-97ed8d4099d8)

iPad:
![77](https://github.com/user-attachments/assets/b017b141-f4fc-4356-af11-21d6a7402cd8)

**Comment by purewhitedesign** [comment]
Problem solved....(in my case)
Update the home assistant app in the app store.

**Comment by slipx06** [comment]
See https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v5.0.0

Linking to other reported problems 
#529 
#511 
#509
#500
