### ISSUE TITLE
ETA to finish battery charge

### ISSUE THREAD

**Issue by usercristi** [slipx06/sunsynk-power-flow-card#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If battery is set to charge up to 90% card still displays time to 100% CHARGE

### Expected behaviour

If battery is set to charge up to 90% card should diplay time to 90% CHARGE

### Possible Solutions

It would be nice to be able to use number.battery_end_of_charge_soc parameter from inverter in card

### Mode

Both

### Context / Reason

For better planning on electricity consumption

**Comment by fraserallanuk** [comment]
Plus one for this Feature Request! 

I actually just submitted one for the opposite - Use an entity for the min discharge valve - https://github.com/slipx06/sunsynk-power-flow-card/issues/520

**Comment by slipx06** [comment]
Hi. The current logic checks if the battery SOC < the current program capacity and if true will set the battery capacity to this value, otherwise if battery SOC > the current program capacity it assumes a charge to 100%. 

What inverter are you using? Do you use a system timer? Is the 90% value apply anytime?

**Comment by usercristi** [comment]
Hello
I am using a Huawei SUN2000-6KTL-L1.It is almost never recommended to charge lithium solar battery to 100% so user can set a parameter whitch limits Max SOC of Battery to a value usually between 80% to 95%.That is why request was to be abble to se manually max SOC value or get it automatically from inverter paramenter
Thank you !
 
 
  Pe lun., oct. 14, 2024 la 19:53, ***@***.***> a scris:   


Hi. The current logic checks if the battery SOC < the current program capacity and if true will set the battery capacity to this value, otherwise if battery SOC > the current program capacity it assumes a charge to 100%.

What inverter are you using? Do you use a system timer? Is the 90% value apply anytime?

**Comment by slipx06** [comment]
Ok let me see what I can do

**Comment by Cyrelion** [comment]
Hello,

I would like to suggest to allow values between 50 and 100. Many of the Senec Batteries are restricted to 70% or even some on 50% of maximum capacity so this would be a good way of use.

**Comment by slipx06** [comment]
@Cyrelion I've pushed this to v5.1.1
