### ISSUE TITLE
Get "shutdown_soc" valve from sensor rather than manually defining.

### ISSUE THREAD

**Issue by fraserallanuk** [slipx06/sunsynk-power-flow-card#520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Inverter: > Battery: > **shutdown_soc:** must be statically defined in the YAML.

Could this be populated by a sensor instead so it is updated from whatever the inverter was set to?

### Expected behaviour

Rather than statically defining the shutdown_soc valve, allow us to enter an entity which holds the valve instead so the valve is pulled from the inverter instead. eg: use valve from: sensor.solis_overdischarge_soc

### Mode

lite

### Context / Reason

Sometimes, I adjust this valve on my inverter. When I do this, I need to go into the sunsynk card code and manually update the shutdown_soc to ensure they match

**Comment by slipx06** [comment]
Hi This is already supported. You can provide a sensor for this attribute i.e.

![image](https://github.com/user-attachments/assets/4f19a569-c09d-4aa3-8e29-1a23e1494343)
