### ISSUE TITLE
Interactive icons

### ISSUE THREAD

**Issue by Sn0w82** [slipx06/sunsynk-power-flow-card#521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the Sun/Invertor/Battery/Grid/Essential/Non-Essential icons are not interactive or cannot be set as interactive.

### Expected behaviour

Give the user the possibility to make them interactive and be able to link to them subviews or other dashboards/tabs

### Mode

Both

### Context / Reason

Usage improvement and coverage of both executive summary that cards gives AND fast dive deeper in details for a specific component if user wants this.

**Comment by slipx06** [comment]
Thanks for the suggestion, Will take a look

**Comment by slipx06** [comment]
@drtinaz this has been added to v5.2.0

**Comment by Sn0w82** [comment]
> @drtinaz this has been added to v5.2.0

Hey slip,

you added for all icons/sections except grid icon/section. In 5.2.0 there is no navigation section available to setup the link under grid section.

**Comment by slipx06** [comment]
@Sn0w82 Its there. Make sure you reset your front end cache

**Comment by Sn0w82** [comment]
I did reset the frontend after initial update and i did now again. Same, i have all other entities navigation tabs but not for grid
![IMG_2156](https://github.com/user-attachments/assets/f7b9b296-7c5f-4511-aab9-e9a46809f99e)

**Comment by slipx06** [comment]
It must still be using the old cached card. 

If you using a browser push F12 and then long press the reload button

![image](https://github.com/user-attachments/assets/36c29c4c-c3e2-4067-ae0b-f3d88fc1e023)

If you are using the IOS companion app. Side bar> app configuration > debugging>reset frontend cache

**Comment by Sn0w82** [comment]
I saw you just pushed an  update. Now grid have navigation tab too and works when pressed. 

Thanks.

**Comment by slipx06** [comment]
It was just an update to the documentation. Anyway glad it’s working.
