### ISSUE TITLE
The TOD SOC display is not correct when prog6 time is earlier than others.

### ISSUE THREAD

**Issue by stealth-eye** [slipx06/sunsynk-power-flow-card#522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The battery area shows two SOC when TOD settings are enabled, current soc and tod soc. The TOD soc is not displayed correctly for most of the day when prog6 time is earlier than others.

![image](https://github.com/user-attachments/assets/6df39a0a-f7f3-4df3-9d59-4834798ead42)

My tod settings: (time in 24hrs)
prog1_time = 11:00
prog2_time = 12:00
prog3_time = 18:00
prog4_time = 22:00
prog5_time = 1:00
prog6_time = 8:00

SOC
prog1_capacity = 65
prog2_capacity = 75
prog3_capacity = 60
prog4_capacity = 50
prog5_capacity = 35
prog6_capacity = 40

During daytime after 8AM, it almost always shows the prog6 capacity instead of current time segment's capacity (as shown in the screenshot, its showing 40%. Screenshot is taken around 4.15PM).

### Expected behaviour

TOD SOC should be shown correctly based on current time.

### Card Version

5.0.0

### Home Assistant Version

2024.10.1

**Comment by slipx06** [comment]
@stealth-eye please test 5.0.1

**Comment by stealth-eye** [comment]
Tested on 5.0.1, Works fine.
Thank you.

**Comment by slipx06** [comment]
Thank you for the coffee 😄

**Comment by stealth-eye** [comment]
The pleasure is all mine. Sincerely grateful for this widget and its documentation. Helped me setup a local dashboard instead of relying on vendor's mobile app.

**Comment by stealth-eye** [comment]
I would like to report a regression on this issue. From 12AM, It is showing "Shutdown SOC" value in the "Runtime to" instead of configured next % slab. 

![Image](https://github.com/user-attachments/assets/879b5dd6-7565-40df-bb99-76009852447b)

**Comment by slipx06** [comment]
Hi. This is by design. When SOC = current program capacity it will show the runtime to shutdown SOC.
