### ISSUE TITLE
Latest version  5.1.1 - Daily Sell does not reset

### ISSUE THREAD

**Issue by wgumaa** [slipx06/sunsynk-power-flow-card#526]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

The daily sell did not reset to 0 after upgrade to the latest version.  

![image](https://github.com/user-attachments/assets/9bc7bf54-4d6c-4f04-9e41-150fb62e40be)

### Expected behaviour

Daily sell should go back to 0 just after midnight

### Card Version

5.1.1

### Home Assistant Version

2024.10.2

**Comment by wgumaa** [comment]
Also the Daily Grid Buy did not reset too.

**Comment by wgumaa** [comment]
It could be a problem from my smart meter

**Comment by slipx06** [comment]
Hi. You will need to check your sensor data. The card just displays the sensor value and will report what it receives

**Comment by wgumaa** [comment]
For some reason, my sensors did not reset and I had to recreate them. Its a sunny day today so I am sending to the grid so at the moment my grid consumed sensor is showing as unknown as there is no electricity coming in at the moment. This is causing my daily load template sensor to show unknown as well.
