### ISSUE TITLE
sunsynk-power-flow-card not working in home assistant mobile app

### ISSUE THREAD

**Issue by basti122303** [slipx06/sunsynk-power-flow-card#539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When home assistant is > 2024.7.4 sunsynk-power-flow-card stop working in mobile app
Web browser like Chromium is working.

- App Version: 2024.10.3-full
- HA Version: 2024.10.4

![Screenshot_20241027-192810_Home_Assistant](https://github.com/user-attachments/assets/0a9f20cb-8bc0-44ab-9070-e49f8d3d08f4)

### Steps To Reproduce

1. Install home assistant > 2024.7.4
2. Install sunsynk-power-flow-card
3. Try to open sunsynk-power-flow-card in mobile app

### Expected behaviour

Work like in web browser

### Card Version

5.3.1

### Home Assistant Version

2024.10.4

**Comment by slipx06** [comment]
Hi This is related to https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v5.0.0

**Comment by basti122303** [comment]
- HA is up to date
- sunsynk-power-flow-card is up to date
- mobile app is up to date

So how should I fix this issue?

**Comment by slipx06** [comment]
I'm not sure. You are running the latest version of the companion app. Have you tried to clear the app cache?

**Comment by basti122303** [comment]
I have clear the cache / user data also try to reinstall the app nothing solved the issue.
On the browser (Firefox / Chromium) all is fine.
In the app also all is fine except sunsynk-power-flow-card

**Comment by slipx06** [comment]
I don't know what else to try. What mobile device and android version are you using? Perhaps other users can help

**Comment by basti122303** [comment]
samsung with android 10, OK Thx, I will try some other versions

**Comment by basti122303** [comment]
I did some more testing, all mobile apps are 2024.10.3-full, HA and Sunsynk Power Flow card are up to date
- Android 14 works
- Android 7 works
- Android 10 (LineageOS) doesn't work in mobile app or browser. I can see the screenshot as above
