### ISSUE TITLE
"Daily Load" not updating

### ISSUE THREAD

**Issue by jplab1983** [slipx06/sunsynk-power-flow-card#54]
For the life of me I am unable to solve this issue - so posting here hoping someone has an easy fix.

My daily Load is not showing any values:
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/33897972/798a940d-5e37-472f-a3c5-014a22115873)

Even though the sensor is correcty mapped:
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/33897972/b894de13-35a1-4981-a13d-d8c2663de877)

And the sensor has a value which is updated as the day goes by:
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/33897972/a04a3d3c-5dec-4161-9c09-cc90719bcea2)

Oh and _Show daily_ is set to _Yes_
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/33897972/a19108c6-51cd-483a-bfd4-535d029c7e80)

**Anyone have an idea why it is not showing up properly?**

**Comment by slipx06** [comment]
Hi. Your entity is not correct. It should be day_load_energy_84:

**Comment by jplab1983** [comment]
Great, thank you! Not sure how that happened. 

Also, thanks for all the hard work you put into this!
