### ISSUE TITLE
Remaining battery energy

### ISSUE THREAD

**Issue by flopp999** [slipx06/sunsynk-power-flow-card#554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/user-attachments/assets/521de77a-d001-4ffc-b6ab-48593f29bd14)
It says remaining is 3.6 kWh but actually I only have 0.6 kWh left because my battery will stop discharge at 10%.
I have set my SoC end to 10%. I have 30000 Wh.

### Expected behaviour

Showing 0 kWh remain when SoC is at 10%

### Possible Solutions

I searched through the code but I couldn't find where the math is done. But remove SoC End before calculate the remaining kWh

### Mode

lite

### Context / Reason

So users don't think there is more kWh than there are

**Comment by flopp999** [comment]
Found it in the code, I will try to make the math as I asking for
https://github.com/slipx06/sunsynk-power-flow-card/blob/706f6f14dbdee815c36edee5457148f7c081c33e/src/cards/full-card.ts#L343

**Comment by slipx06** [comment]
Hi
At the moment the remaining energy is calculated based on total battery capacity and not shutdown SOC.

**Comment by flopp999** [comment]
OK, what do you think of changing that?
I fix until that will be implemented is to change the shutdown SoC to 0% and the amount of energy

**Comment by slipx06** [comment]
Le me think about adding both options
