### ISSUE TITLE
v 6.1.2 broke card without solar

### ISSUE THREAD

**Issue by OwlBawl** [slipx06/sunsynk-power-flow-card#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using your card in Compact view without Solar Panels
After last update my TOP "margin" went wrong, I see spacer for like Solar is enabled, but it's just empty.
Before inverter was much closer to top of the card... I have Solar disabled in settings.

![IMG_8907](https://github.com/user-attachments/assets/59aa173e-0a44-4c38-a58b-6933192e9da2)

### Expected behaviour

Hide Solar margin / spacer if "disabled"

### Card Version

6.1.2

### Home Assistant Version

2024.11.3

**Comment by slipx06** [comment]
Hi. Yes with the new grouping of SVG elements I had to make some changes. I'm busy testing at the moment to try revert the original view.
