### ISSUE TITLE
Home Production Anomaly

### ISSUE THREAD

**Issue by MaurizioBarbera** [slipx06/sunsynk-power-flow-card#565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

You use solar production and no inverte output. the HUAWEI SUN2000 it has two sensors for the inverter one input power to the inverter and another which is the active power (output), it is possible to use in the calculation: inverte_power_175 and not pv1_power_186...

doc: Home Production = Solar + Battery (discharge) + Aux (in)
change on: Home Production = inverter_power_175 + Battery (discharge) + Aux (in)
thanks and confident in your exhaustive answer the question

### Expected behaviour

Ratio and autarky more precise

### Card Version

6.1.3

### Home Assistant Version

2024.11.0

**Comment by slipx06** [comment]
Hi. That logic is only used to display the additional Autarky and Ratio stats. Removing Solar or creating a custom formula does not really make sense for the majority of users. You should rather hide that information if it is inaccurate for your setup by setting `autarky: no`

**Comment by MaurizioBarbera** [comment]
hi, okay thanks

Inviato da Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: slipx06 ***@***.***>
Inviato: Friday, December 6, 2024 1:34:00 PM
A: slipx06/sunsynk-power-flow-card ***@***.***>
Cc: MaurizioBarbera ***@***.***>; Author ***@***.***>
Oggetto: Re: [slipx06/sunsynk-power-flow-card] Home Production Anomaly (Issue #565)


Hi. That logic is only used to display the additional Autarky and Ratio stats. Removing Solar or creating a custom formula does not really make sense for the majority of users. You should rather hide that information if it is inaccurate for your setup by setting autarky: no
