### ISSUE TITLE
EaSun SMGII add connection

### ISSUE THREAD

**Issue by amgstone** [slipx06/sunsynk-power-flow-card#568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have been fighting for a long time so that my electricity consumption at home is correctly displayed, but while the sun is working + the battery on the house visualizes the consumption from the network, although there is no consumption

There is a project on github where the inverter is connected to the home assistant, I use it, everything works correctly, but when I transfer all the data to the sunsynk-power-flow-card, it does not correctly visualize the consumption of the house

https://github.com/syssi/esphome-smg-ii

![xxx](https://github.com/user-attachments/assets/84aadcce-7d5f-4bf2-ba28-b6e6e89f95e6)

### Expected behaviour

I have been fighting for a long time so that my electricity consumption at home is correctly displayed, but while the sun is working + the battery on the house visualizes the consumption from the network, although there is no consumption

There is a project on github where the inverter is connected to the home assistant, I use it, everything works correctly, but when I transfer all the data to the sunsynk-power-flow-card, it does not correctly visualize the consumption of the house

https://github.com/syssi/esphome-smg-ii

![xxx](https://github.com/user-attachments/assets/84aadcce-7d5f-4bf2-ba28-b6e6e89f95e6)

### Mode

full

### Context / Reason

I have been fighting for a long time so that my electricity consumption at home is correctly displayed, but while the sun is working + the battery on the house visualizes the consumption from the network, although there is no consumption

There is a project on github where the inverter is connected to the home assistant, I use it, everything works correctly, but when I transfer all the data to the sunsynk-power-flow-card, it does not correctly visualize the consumption of the house

https://github.com/syssi/esphome-smg-ii

![xxx](https://github.com/user-attachments/assets/84aadcce-7d5f-4bf2-ba28-b6e6e89f95e6)

**Comment by slipx06** [comment]
Hi. What sensor are you using for `essential_power` ?
According to your image the battery is discharging ?

**Comment by slipx06** [comment]
Ok the problem is the calculation does not take into consideration any inverter loss. Which in your case 72W

859 - (447+340)

I'll see if I can improve the logic for that
