### ISSUE TITLE
reverse flow with battery

### ISSUE THREAD

**Issue by DJTech84** [slipx06/sunsynk-power-flow-card#569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,
I ask for help because for months I have been trying various configurations without success, I have come to the conclusion that the problem is probably not in the card but perhaps my Voltronic inverter does not work with this card.

The problem concerns the direction of the current flow of my battery, I have **"sensor.inverter_battery_load"** which if it is charging (from panels) presents positive values ​​from **0** or **>0** and if instead it is discharging it presents negative values ​​**(-1)**. 
I have read the documentation several times on how and where to set the sensors for the flow or power direction but in my case this does not work, it always remains stable in one direction.

For me it would solve the problem if there was a way to control the **"invert_power:"** parameter (false for discharging or true for charging) based on the value of the positive or negative sensor. 
I ask for help from the developer or anyone who has found a solution if they can tell me how to solve the problem.
Many compliments for the card :)

### Expected behaviour

The problem concerns the direction of the current flow of my battery, I have **"sensor.inverter_battery_load"** which if it is charging (from panels) presents positive values ​​from **0** or **>0** and if instead it is discharging it presents negative values ​​**(-1)**. 
I have read the documentation several times on how and where to set the sensors for the flow or power direction but in my case this does not work, it always remains stable in one direction.

### Card Version

V6.1.4

### Home Assistant Version

home assistant core 14.0.rc2

### Configuration

```shell
type: custom:sunsynk-power-flow-card
cardstyle: full
show_solar: true
battery:
  show_daily: false
  auto_scale: true
  show_absolute: false
  invert_power: false
  charge_colour:
    - 4
    - 255
    - 0
  colour:
    - 255
    - 0
    - 0
  energy: 4800
  dynamic_colour: true
  linear_gradient: true
  hide_soc: false
  animate: true
  show_remaining_energy: true
  animation_speed: 12
  invert_flow: true
  max_power: 9600
  soc_end_of_charge: 100
  shutdown_soc_offgrid: 32
  shutdown_soc: 25
  count: 1
solar:
  show_daily: true
  mppts: 1
  pv1_name: Pannelli
  auto_scale: true
  colour:
    - 238
    - 255
    - 0
  dynamic_colour: true
  animation_speed: 24
  display_mode: 3
  max_power: 6000
  pv1_max_power: 7250
load:
  show_daily: false
  auto_scale: true
  dynamic_colour: true
  colour:
    - 0
    - 219
    - 205
  dynamic_icon: true
  essential_name: CASA
  load1_name: DEUMIDIFICATORE
  load1_icon: mdi:air-humidifier
  load2_name: Lavastoviglie
  load2_icon: mdi:dishwasher
  load4_icon: mdi:home-floor-2
  load4_name: App_B
  load3_name: App_A
  load3_icon: mdi:home-floor-1
  load5_name: Lavatrice
  load5_icon: mdi:washing-machine
  load6_name: Asciugatrice
  animation_speed: 13
  max_power: 6000
  additional_loads: 6
  load6_icon: mdi:washing-machine
grid:
  show_daily_buy: false
  show_daily_sell: false
  show_nonessential: true
  grid_off_colour:
    - 195
    - 218
    - 16
  no_grid_colour:
    - 156
    - 156
    - 156
  auto_scale: false
  invert_grid: false
  colour:
    - 25
    - 160
    - 227
  show_absolute: false
  export_colour:
    - 141
    - 25
    - 164
  grid_name: ENEL
  energy_cost_decimals: 0
  max_power: 6000
  disconnected_icon: mdi:transmission-tower-off
  off_threshold: 100
  nonessential_name: "Termo"
  nonessential_icon: mdi:heating-coil
entities:
  use_timer_248: switch.sunsynk_toggle_system_timer
  day_battery_charge_70: sensor.sunsynk_day_battery_charge
  day_battery_discharge_71: sensor.sunsynk_day_battery_discharge
  day_grid_import_76: sensor.sunsynk_day_grid_import
  day_grid_export_77: sensor.sunsynk_day_grid_export
  day_load_energy_84: sensor.sunsynk_day_load_energy
  essential_power: sensor.inverter_ac_out_watt
  day_pv_energy_108: sensor.inverter_pv_generation_day
  pv1_power_186: sensor.inverter_pv_charging_power
  pv1_voltage_109: sensor.inverter_pv_input_voltage
  pv1_current_110: sensor.inverter_pv_input_current
  inverter_voltage_154: sensor.inverter_ac_in_voltage
  load_frequency_192: sensor.inverter_ac_in_frequenz
  priority_load_243: sensor.inverter_ac_in_rating_current
  inverter_power_175: sensor.inverter_ac_out_watt
  grid_power_169: sensor.misuratore_consumi_potenza
  total_pv_generation: sensor.inverter_pv_generation_year
  essential_load1: sensor.deumidificatore_potenza
  essential_load2: sensor.lavastoviglie_potenza
  grid_voltage: sensor.misuratore_consumi_tensione_2
  essential_load4: sensor.carichi_app_b_potenza
  environment_temp: sensor.openweathermap_temperature
  essential_load4_extra: sensor.carichi_app_b_potenza
  grid_connected_status_194: "off"
  inverter_status_59: sensor.inverter_inverter_operation_mode
  inverter_current_164: sensor.misuratore_consumi_corrente_2
  grid_ct_power_172: sensor.potenza_corretta_2
  nonessential_power: sensor.consumo_termo_3
  battery_rated_capacity: sensor.inverter_battery_percent
  battery_current_191: sensor.inverter_battery_load
  battery_temp_182: sensor.inverter_battery_temperature
  battery_voltage_183: sensor.inverter_battery_voltage
  battery_power_190: sensor.inverter_ac_out_watt
  battery_soc_184: sensor.inverter_battery_percent
large_font: true
panel_mode: true
show_battery: true
show_grid: true
decimal_places: 1
dynamic_line_width: true
max_line_width: 7
min_line_width: 2
inverter:
  auto_scale: false
  modern: true
  colour:
    - 188
    - 99
    - 191
  autarky: "no"
  model: solis
grid_options:
  columns: full
wide: true
title: in test
battery2:
  energy: 4800
  shutdown_soc: 25
  soc_end_of_charge: 100
  shutdown_soc_offgrid: 32
  dynamic_colour: true
  animate: true
  show_remaining_energy: true
  linear_gradient: true
  colour:
    - 255
    - 0
    - 0
  charge_colour:
    - 43
    - 255
    - 0
```

**Comment by DJTech84** [comment]
Hi,
the issue with the direction of the animation

I am replying a bit late because I have done various tests with the various suggested settings, at the moment the battery is in the discharge phase. To obtain the discharge flow I have to set with invert_flow: true and invert_power: true (for me it is red with animation towards inverter, instead for the charge it should become green with animation towards battery with positive value.)

To avoid waiting until tomorrow at the moment I am simulating with a virtual sensor through a slider the Ampere current with positive and negative values, but even changing true and false I do not find changes in direction.
<img width="395" alt="Screenshot 2024-12-06 alle 17 55 10" src="https://github.com/user-attachments/assets/7dddf32b-3c8d-433c-9c8d-e4e764b895de">

**Comment by DJTech84** [comment]
Hi,
the issue with the direction of the animation

I am replying a bit late because I have done various tests with the various suggested settings, at the moment the battery is in the discharge phase. To obtain the discharge flow I have to set with invert_flow: true and invert_power: true (for me it is red with animation towards inverter, instead for the charge it should become green with animation towards battery with positive value.)

To avoid waiting until tomorrow at the moment I am simulating with a virtual sensor through a slider the Ampere current with positive and negative values, but even changing true and false I do not find changes in direction.<img width="395" alt="Screenshot 2024-12-06 alle 18 03 41" src="https://github.com/user-attachments/assets/afc81235-fdfb-46aa-8552-27eb9817f7d8">

**Comment by slipx06** [comment]
The direction of flow is set by the battery power value not current.  Try creating a template sensor for battery power and see the effects. 

```
invert_flow: true 
invert_power: false
```

**Comment by DJTech84** [comment]
> The direction of flow is set by the battery power value not current. Try creating a template sensor for battery power and see the effects.
> 
> ```
> invert_flow: true 
> invert_power: false
> ```

Great, I noticed differences, I did the required tests, always using a slider for negative values, 0 and positive values ​​in the power section the flow changes direction and color as you indicated.

Maybe my inverter model "InfiniSolar V IV" is not completely compatible with this card, because it manages the power ONLY POSITIVE, these always remain positive values ​​or 0.

What distinguishes whether the battery is in a charge or discharge state are the Amperes with which it charges, Example -2, 0, +2 defined by the sensor "sensor.inverter_battery_load".

the problem remains that to make the flow work I have to insert sensor.inverter_battery_load displaying A instead of sensor.inverter_ac_out_watt which displays the W.

could this inverter be implemented in the future?
<img width="316" alt="Screenshot 2024-12-07 alle 08 28 18" src="https://github.com/user-attachments/assets/d1d573fa-611b-499b-884d-ebc68e0bbed1">

**Comment by slipx06** [comment]
You can create a helper that inverts your sensor.inverter_ac_out_watt when sensor.inverter_battery_load is negative. Here is an example to start with

```
template:
  - sensor:
      - name: "AC Out Watt with Sign"
        unique_id: "ac_out_watt_signed"
        state: >
          {% if states('sensor.inverter_battery_load') | float < 0 %}
            {{ (states('sensor.inverter_ac_out_watt') | float) * -1 }}
          {% else %}
            {{ states('sensor.inverter_ac_out_watt') | float }}
          {% endif %}
        unit_of_measurement: "W"
        device_class: power
```

**Comment by DJTech84** [comment]
> You can create a helper that inverts your sensor.inverter_ac_out_watt when sensor.inverter_battery_load is negative. Here is an example to start with
> 
> ```
> template:
>   - sensor:
>       - name: "AC Out Watt with Sign"
>         unique_id: "ac_out_watt_signed"
>         state: >
>           {% if states('sensor.inverter_battery_load') | float < 0 %}
>             {{ (states('sensor.inverter_ac_out_watt') | float) * -1 }}
>           {% else %}
>             {{ states('sensor.inverter_ac_out_watt') | float }}
>           {% endif %}
>         unit_of_measurement: "W"
>         device_class: power
> ```

thank you so much, it seems to work well now.
I take this opportunity to ask if the yellow line coming from the panels is normal for it to be shorter (it is far from the inverter) in wide view or if I did something wrong.
<img width="377" alt="Screenshot 2024-12-07 alle 10 17 14" src="https://github.com/user-attachments/assets/7cbf069e-dc8b-4a3b-8b51-7134f8bab149">

**Comment by slipx06** [comment]
That looks like a bug. Let me investigate
