### ISSUE TITLE
Hide additional loads when power is below limit (0)

### ISSUE THREAD

**Issue by cm86** [slipx06/sunsynk-power-flow-card#577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Additional Load is showing with value 0

### Expected behaviour

 there should be an option to hide the load if the power is below a limit or 0.

### Possible Solutions

ad an option for that... :)

### Mode

lite

### Context / Reason

like described

**Comment by slipx06** [comment]
Why not just enable dynamic colour and use the off_threshold to grey our loads that are off.  I could also add an option to set the off colour and you can set it to transparent to hide the load instead of the default grey.

**Comment by cm86** [comment]
As you can see it's already colored gray when the load is 0.

But as my washing machine and the tumble dryer aren't on all the day i would hide them when they are off...

![Bildschirmfoto 2024-12-17 um 23 32 06](https://github.com/user-attachments/assets/b0eed4b0-c0e1-4c66-93aa-2836e3f49060)

thanks for your reply

**Comment by slipx06** [comment]
OK, I've added an option to set the off colour for the additional load. When you set it to 'transparent' it will hide the load when <= off threshold

Off colour set to default grey
![{BC35BD44-CBAF-4E4A-9805-7F9381C8415F}](https://github.com/user-attachments/assets/e5e4cddf-5b6a-4536-89de-d17ea0213947)

Off colour set to transparent
![{87D0D4E9-594C-47BF-B781-8910A6F57F5C}](https://github.com/user-attachments/assets/9c2d6555-cc69-4bf3-b9db-bf2d9e682a3a)

**Comment by cm86** [comment]
Nice - Thanks.
i think i can test this in the next release?!

Mit freundlichen Grüßen
Chris

**Comment by alphabravocharly72** [comment]
Nice feature, but cant find the transparent button. Or do I need to set the RGB colors?

**Comment by slipx06** [comment]
@alphabravocharly72  you cant set it via the visual editor. Switch to the code editor and change the `off_colour` attribute in the load section  to `transparent`.

**Comment by alphabravocharly72** [comment]
thx for the hint.
Added the off_colour manualy and it works perfectly.
Again thx for your feedback ;-)
