### ISSUE TITLE
It is not rendering well on Android 5.x

### ISSUE THREAD

**Issue by danielTinkiel** [slipx06/sunsynk-power-flow-card#582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Even though HA companion claims to be compatible with Android 5.0 and up, when displayed on a 5.x Android device it does not display well. On current Android devices it does work well.

### Expected behaviour

I expect to see my HA like in any other more modern Android Version

### Card Version

6.2

### Home Assistant Version

2024.12.1

**Comment by slipx06** [comment]
Hi. Please see https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v5.0.0
