### ISSUE TITLE
Aux_Load2 shows incorrect entity.

### ISSUE THREAD

**Issue by djagerif** [slipx06/sunsynk-power-flow-card#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you click on Aux_Load2 the popup brings up Aux_Load1's data.

### Steps To Reproduce

Just click on Aux_Load2 to verify the entity to be from Aux_Load1.

### Expected behaviour

Show Aux_Load2's entity data. The issue might be here (see below).

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/5621764/cc66ab03-456f-458c-afa4-d95baaedf2ad)

### Card Version

2.0.0

### Home Assistant Version

2023.8.3

### Configuration

```shell
<N/A>
```

### Relevant log output

```shell
<N/A>
```

**Comment by slipx06** [comment]
Thanks for catching that. Will fix.
