### ISSUE TITLE
Show the Octopus Export and Import rate depending on direction

### ISSUE THREAD

**Issue by bazcurtis** [slipx06/sunsynk-power-flow-card#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Shows the import rate

### Expected behaviour

Currently works as designed

### Possible Solutions

Show the Octopus Export and Import rate depending on direction. Change colour or add an arrow and show the current price depending on if you are importing or exporting

### Mode

Both

### Context / Reason

It shows importing all the time, even if you are exporting. I thought it might be nice to the price on what is happening at the time.

This is the best energy card out there for Home Assistant in my view.

**Comment by slipx06** [comment]
Hi. I have no way of testing this so will need a bit more information. 
The card shows import or export based on the animated power flow and the power value (+-). 
Does Octopus provide separate sensors when importing or exporting?

**Comment by marksie1988** [comment]
> Hi. I have no way of testing this so will need a bit more information. The card shows import or export based on the animated power flow and the power value (+-). Does Octopus provide separate sensors when importing or exporting?

The octopus integration provides the price for import and price for export. 

assuming I understand correctly, we could update the `energy_cost` with the following: 

```
export_price
import_price
```

Then depending on the  flow of the electricity we can pick which of these options to use?

**Comment by bazcurtis** [comment]
I am using this [Integration](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/)

it has these two sensors.

sensor.agile_current_import_rate
sensor.agile_current_export_rate

I am happy to do any testing if you decide to implement this

<img width="559" alt="Screenshot 2023-08-25 at 09 40 38" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/7840697/66bbf9a9-0e2a-45e1-abe8-b79932515220">

**Comment by slipx06** [comment]
Ok I understand. It can be implemented as per @marksie1988 suggestion above

**Comment by slipx06** [comment]
I've added this to https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/2.2.0

<html>
<body>


Attribute | Requirement | Default | Description
-- | -- | -- | --
energy_cost_buy: | Optional |   | Sensor that provides current buy energy cost per kWh
energy_cost_sell: | Optional |   | Sensor that provides current sell energy cost per kWh


</body>
</html>

The card will display the correct cost based on grid power

**Comment by bazcurtis** [comment]
Thanks for adding this. The sun has just gone in and I am using the battery 😄. I will check it.

**Comment by bazcurtis** [comment]
Working fantastic. Thank you very much.

**Comment by bazcurtis** [comment]
Working fantastic. Thank you very much.
