### ISSUE TITLE
Show PV3 Voltage an Current is overlapping after latest update

### ISSUE THREAD

**Issue by hddmax** [slipx06/sunsynk-power-flow-card#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

PV3 Voltage an Current is overlapping
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/125349508/6e5959af-012e-49f6-ab54-66a9f5ca8fbd)

### Expected behaviour

PV3 Voltage an Current is overlapping

### Card Version

2.1.0

### Home Assistant Version

2023.8.3

**Comment by slipx06** [comment]
Thanks for catching that. Will fix it

**Comment by slipx06** [comment]
fixed in 2.1.2
