### ISSUE TITLE
Battery inverse animation

### ISSUE THREAD

**Issue by krime777** [slipx06/sunsynk-power-flow-card#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When battery_current_191 is negative the battery is feeding the inverter, when it's positive the battery is charging.
The animation is the other way around, when the battery is discharging (battery_current_191 is negative) the dot moves from the inverter to the battery and on charging the dot moves from the battery to the inverter.

### Expected behaviour

The dot between battery and inverter should move the other way.

### Card Version

2.1.2

### Home Assistant Version

2023.08.1

**Comment by slipx06** [comment]
HI. There is an option to invert your battery flow. Refer to the invert_power: attribute under the battery card configuration

https://slipx06.github.io/sunsynk-power-flow-card/configuration.html

The flow direction is based on the battery power value.

<html>
<body>


invert_power: | Optional | false | Set to true if your sensor provides a positive number for battery charge and negative number for battery discharge
-- | -- | -- | --



</body>
</html>
