### ISSUE TITLE
battery discharge sensor

### ISSUE THREAD

**Issue by amgstone** [slipx06/sunsynk-power-flow-card#72]
![Screenshot_2023-08-30-15-27-44-461_io homeassistant companion android](https://github.com/slipx06/sunsynk-power-flow-card/assets/63303107/5405834c-117c-4cdb-9661-fc845264b44c)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a sensor in a 2 in 1 inverter that shows both charge and discharge. when I connected the sensor, it constantly shows that the battery is discharging, even when it is charging. during discharge it displays "-".

### Expected behaviour

battery discharge sensor

### Possible Solutions

I have a sensor in a 2 in 1 inverter that shows both charge and discharge. when I connected the sensor, it constantly shows that the battery is discharging, even when it is charging. during discharge it displays "-".

### Mode

lite

### Context / Reason

I have a sensor in a 2 in 1 inverter that shows both charge and discharge. when I connected the sensor, it constantly shows that the battery is discharging, even when it is charging. during discharge it displays "-".

**Comment by slipx06** [comment]
HI. Please can you share your card configuration and a screenshot of the issue.

**Comment by amgstone** [comment]
![Screenshot_2023-08-30-16-45-50-870_io homeassistant companion android](https://github.com/slipx06/sunsynk-power-flow-card/assets/63303107/1ddab28f-d4e2-4af0-ab76-59994f45f56f)

**Comment by amgstone** [comment]
charge
![Screenshot_2023-08-30-16-48-54-002_io homeassistant companion android](https://github.com/slipx06/sunsynk-power-flow-card/assets/63303107/b22ba910-f22d-4295-acdf-623c6d310566)

**Comment by slipx06** [comment]
The battery power will always be displayed as a positive number. Does the the dot move in the correct direction when charging and discharging? If not you can use the invert option

**Comment by amgstone** [comment]
always shows a positive number

**Comment by slipx06** [comment]
Yes that's correct. Please refer to the documentation 
https://slipx06.github.io/sunsynk-power-flow-card/configuration.html#battery


![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/64b28183-eec5-4b92-b754-57fed21e2198)

**Comment by amgstone** [comment]
![Screenshot_2023-08-30-18-48-19-224_io homeassistant companion android](https://github.com/slipx06/sunsynk-power-flow-card/assets/63303107/c7ee4d18-bb14-449c-94a1-1f823ded2faf)

now it is charging, but the charging status visualizes that it is being discharged and increases the time until it is fully discharged

**Comment by amgstone** [comment]
when charging it should show "charging" status, am i misunderstanding something?

**Comment by amgstone** [comment]
![Screenshot_2023-08-30-19-02-37-028_io homeassistant companion android](https://github.com/slipx06/sunsynk-power-flow-card/assets/63303107/20ee25bc-26e2-4a28-925a-fc17042312da)
I have -1.4 amps and -79 watts at a time on the battery. and it shows that I have 79 watts without "-".

**Comment by slipx06** [comment]
The card will never show a negative number for battery power, regardless of what your sensor value is. If needed you can invert the battery power.

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/0f9cbf74-7d0b-4a94-b265-c8e6d0f62e6f)

**Comment by amgstone** [comment]
![Screenshot_2023-08-30-20-25-05-528_io homeassistant companion android](https://github.com/slipx06/sunsynk-power-flow-card/assets/63303107/85904b9b-92ea-4af5-9189-b562f2a193dd)
added, it works, but tomorrow I will see how it will work when the battery is charged from the sun

**Comment by amgstone** [comment]
also tell me where to enter what, I can't add an electric car to the input load

**Comment by slipx06** [comment]
You can add an additional load to the essential side and enable in your config. Its all documented.

<html>
<body>


additional_loads: | Optional | 0 | Display additional loads on the essential side (0/1/2)
-- | -- | -- | --
load1_name: | Optional |   | Set the display name for the essential load 1
load2_name: | Optional |   | Set the display name for the essential load 2
load1_icon: | Optional | none | Change the essential load 1 image using preset or any mdi icon e.g. mdi:ev-station Presets are: boiler, pump, aircon, oven
load2_icon: | Optional | none | Change the essential load 2 image using preset or any mdi icon e.g. mdi:ev-station Presets are: boiler, pump, aircon, oven


</body>
</html>

<html>
<body>


essential_load1: | Optional |   | Sensor that contains the power of your essential load 1 (W)
-- | -- | -- | --



</body>
</html>

**Comment by amgstone** [comment]
thank you very much, everything works
![IMG_20230831_130617](https://github.com/slipx06/sunsynk-power-flow-card/assets/63303107/de71ff7d-1644-4977-aa8c-396d6ce6173f)
