### ISSUE TITLE
Smaller 'Liter' interface

### ISSUE THREAD

**Issue by darren-arbon** [slipx06/sunsynk-power-flow-card#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The lite version for me has much more information that I really want in an at-a-glance view

### Expected behaviour

A smaller view that is much more simplistic

### Possible Solutions

I have already forked your library and added my own there, but I was wondering if you would like me to raise a PR to add it to your package so you can see it in action.

### Mode

lite

### Context / Reason

The reason I have added a smaller version is that the current lite version has a large footprint, and does contain information that is not too important if you just want an at-a-glance view

**Comment by slipx06** [comment]
Hi. Can you share a screenshot? Most things can be turned off so interested to see what you came up with.

**Comment by darren-arbon** [comment]
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/81559178/0e989dab-6ecf-4287-9708-6887704e5f9e)

If I can turn things off to get this kinda view I would be very happy!!

**Comment by slipx06** [comment]
So by smaller, you mean the actual height of the card? You can disable sensors to create the view below

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/20a90869-a99e-49f2-9a38-a7b9be23651b)

**Comment by darren-arbon** [comment]
Yes, a smaller height of the card. I want this information, but with less real estate.

**Comment by slipx06** [comment]
Ok. For now you can set the card height but it does make things a bit small
```
type: custom:sunsynk-power-flow-card
cardstyle: lite
show_solar: true
card_height: 315px
```
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/8e313037-8d5a-4517-9e99-75d6672a0d1f)

**Comment by darrenarbon** [comment]
Cheers, I'll have a play and see what happens
