### ISSUE TITLE
How to remove a battery from the chart?

### ISSUE THREAD

**Issue by home409ca** [slipx06/sunsynk-power-flow-card#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

How to remove a battery from the chart?
I don't have energy storage and I would like to use this flow card with my inverter

### Expected behaviour

add function

### Mode

both

### Context / Reason

show_battery: false

**Comment by slipx06** [comment]
Will take a look at adding this

**Comment by slipx06** [comment]
Added to [2.5.1](https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v2.5.1)
