### ISSUE TITLE
Title of the card is missing.

### ISSUE THREAD

**Issue by kunwarf** [slipx06/sunsynk-power-flow-card#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is no config available to set the title of the card. Also if the name/image of the inverter can be set then it would be great.

### Expected behaviour

There should be a config for setting up the title of the card also Also if the name/image of the inverter can be set then it would be great.

### Mode

Both

### Context / Reason

I have three different inverters and battery banks installed. I am using three cards for these systems but could not differentiate between them on the dashboard so if a title field would be added then it would be great.

**Comment by slipx06** [comment]
HI. There are other ways to do this on your dashboard with title card or markup card i.e. custom:mushroom-title-card.  I'll see what I can do but given the limited card space it may not be practical.

**Comment by slipx06** [comment]
Hi
Added to https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v2.6.0
Update you card configuration with

```
type: custom:sunsynk-power-flow-card
cardstyle: full
show_solar: true
show_battery: true
large_font: true
title: Sunsynk Inverter
title_colour: Grey
title_size: 32px
```

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/286daad7-334d-4b02-95ed-0c3cbce40a4a)

**Comment by kunwarf** [comment]
Thanks for your quick response.
