### ISSUE TITLE
2 phase or 3 phase support 

### ISSUE THREAD

**Issue by vinaytje94** [slipx06/sunsynk-power-flow-card#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Card only shows values for single phase inverters ,
![Screenshot_20230919_090342_Home Assistant](https://github.com/slipx06/sunsynk-power-flow-card/assets/110492139/18f19d01-7b73-4b8c-9f86-b273dfdc7158)
I have 2 ct clamps for grid l1 l2
And have voltages for l1 and l2

### Expected behaviour

Is it possible to add a second row for the second ct sensor, or just combine both?
Also the same for the grid voltage phase A / phase B or phase AB combined, and current A B values.
I think it would be easier to implement for three phase with the option to hide the hide the parameters

### Mode

full

### Context / Reason

I have a US version of the Deye hybrid inverter. It reports 2 phase values, ct a b powers and  phase a b voltages, a b currents too

**Comment by Mights001** [comment]
Hi, 

First of all, I'm really excited about the card.

I would also like if you could integrate that so that I could see all 3 phases


![grafik](https://github.com/slipx06/sunsynk-power-flow-card/assets/35522918/bb83378d-9df9-4785-8843-9b3ed0247161)

I just change the javascript self, but they did not work ;( 

Many Thanks in Adv.

**Comment by slipx06** [comment]
Hi. Can you share the sensor data that you want displayed as I don't have a 3 phase inverter to test.

**Comment by vinaytje94** [comment]
> Hi. Can you share the sensor data that you want displayed as I don't have a 3 phase inverter to test.

Hey there, 

Please see the highlighted areas
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/110492139/318ae3ff-2eb2-4f84-9d3f-1ef29293a4c0)

I currently have it configured like this
inverter_voltage_154: sensor.deye_voltage_l1                    /// free sensor: sensor.deye_voltage_l2
inverter_current_164: sensor.deye_current_l1                    ///  free sensor: sensor.deye_current_l2
grid_ct_power_172: sensor.deye_external_ct_l1_power     ///  free sensor: sensor.deye_external_ct_l2_power

Free sensor just means the 2nd phase, not being shown, for 3ph it wouldve been l2 and l3

I dont mind if grid ct can be combined for a total value (just like total pv).
But i think it would be handier to implement a second row below the values or besides it. You might have to increase the size of the square container to accommodate the values.

**Comment by Mights001** [comment]
In my case there are 2 more values ​​for each Phase voltage and current L1-L2-L3 .
But the Modbus Addresses are not simular to the Sunsynk Invter, but that is not really importantent. 
![grafik](https://github.com/slipx06/sunsynk-power-flow-card/assets/35522918/a31e0c99-c14a-4f6c-af01-399b9980d977)

For the load displays, it would also be great if you could include a choice between watts and kilowatts :) 

THX Mights

**Comment by slipx06** [comment]
Ok. Still thinking about how we can achieve this. @Mights001 2.7.0 adds an option to display kW

**Comment by Legnava89** [comment]
For the 3F inverter, I created a template in HA as a sensor.
Example for Goodwe

`  - sensor:
      - name: Napětí střídač
        unique_id: napeti
        unit_of_measurement: "V"
        state: "{{ (states('sensor.nbus_voltage') | float) + ( states('sensor.bus_voltage') | float) }}"
        icon: mdi:lightning-bolt
        
  - sensor:
      - name: Ampéry střídač
        unique_id: ampery
        unit_of_measurement: "A"
        state: "{{ (states('sensor.on_grid_l1_current') | float) + ( states('sensor.on_grid_l2_current') | float) + ( states('sensor.on_grid_l3_current') | float) }}"
        icon: mdi:lightning-bolt`

![ampery](https://github.com/slipx06/sunsynk-power-flow-card/assets/145229528/f5449b4f-6949-493c-95bb-d391d8b5a89f)

**Comment by chinezbrun** [comment]
i'm interested too.

**Comment by slipx06** [comment]
These are the mock-ups I have. 
It should be possible to do something like this on the lite card?

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/7a48607c-a3ae-40f1-be55-434a1d1f6b09)

and the full card becomes a cramped but it could work 

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/c2d0a9cd-1663-418f-860f-6496ddf88097)

**Comment by Mights001** [comment]
Hey, that looks good. On the Lite card it might be better if you display the first voltage eache phase and than Amp and last Frequency.

**Comment by slipx06** [comment]
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/a303391a-d2fb-49d0-8940-3f860875fc4c)

**Comment by slipx06** [comment]
Full card. You will notice that I've had to reduce decimal places show for current on the full card and voltage on the lite card to prevent overlap issues. Its a small compromise

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/b129dc96-71ac-4b34-a29c-385bde9299e9)

**Comment by vinaytje94** [comment]
> Full card. You will notice that I've had to reduce decimal places show for current on the full card and voltage on the lite card to prevent overlap issues. Its a small compromise
> 
> ![image](https://user-images.githubusercontent.com/7227275/274987271-b129dc96-71ac-4b34-a29c-385bde9299e9.png)

Hey slip, this looks good.
Have you added perhaps a show option for the L2/3 phases.
Is it possible to add the currents like how the voltages are listed so that the form looks uniform

**Comment by vinaytje94** [comment]
Right now i have updated and adjusted mine with a micro inverter on the aux input. It looks like this
![Screenshot_20231013_210116_Home Assistant](https://github.com/slipx06/sunsynk-power-flow-card/assets/110492139/469d2bb4-20ed-477c-bb01-c07a8d0de036)

**Comment by slipx06** [comment]
HI. There just isn't enough space on the card for uniformity e.g. if you have 4 mppt's 
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/c70a05e6-ea23-4cd0-b55a-cf684e868d5f)
I'm busy looking at adding L1-L3 and external CT L1-L3

**Comment by slipx06** [comment]
These are the final version. Will be pushing this soon

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/3a265c23-fd22-4265-ad01-7a452674050a)

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/376d059b-aba7-4e71-affc-d59965afc68e)

**Comment by slipx06** [comment]
See https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v2.11.0

**Comment by Legnava89** [comment]
Hi, in the lite card there is a problem with the graphics of the energy_cost_sell entity

![entita](https://github.com/slipx06/sunsynk-power-flow-card/assets/145229528/eef5ac87-2609-4649-a94c-c8c128f92897)

**Comment by slipx06** [comment]
Thanks for catching that. Fixed in [2.11.1](https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v2.11.1)

**Comment by vinaytje94** [comment]
Finally got the time to check the updates. Looks like this
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/110492139/dd048a6a-ca42-4f2a-aaef-2d4c85eda359)

**Comment by slipx06** [comment]
I'm going to fix the NaN on the daily total. You can also use `inverter_current_L3:` to display your L2 current if you want to change layout a bit.
