### ISSUE TITLE
Refactor display when Aux is an input

### ISSUE THREAD

**Issue by jpettitt** [slipx06/sunsynk-power-flow-card#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Au is a power source (eg a generate) it would be preferable to move it to a different location since the load side is somewhat cluttered.   Additionally the Ow box above the inverter is confusing in that isually is inplies power from the grid is flowing through it but it's showing 0W

<img width="446" alt="image" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/524856/45376089-343a-4215-93d3-b7b23a181ea3">

### Expected behaviour

les cluttered screen,  central node not showing 0W

### Possible Solutions

Move the generator to bottow left (add a dedicated "generator" type or a flag for the aux indicating it's a generator.

Remove the redundant `0W` from the central node or reroute the connections.

### Mode

full

### Context / Reason

cluttered display, confusing value

**Comment by slipx06** [comment]
Hi. A quick fix could be to change the AUX icon to represent a generator. Power flow is then represented through the animated dot.

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/ab62d3e6-2cef-4f5c-a6d6-06c7e8dca3e0)

As mentioned in your other issue those sensor values are specific to the original design intent and the Sunynk registers displayed on the system flow screen. You could hide the value by setting inverter_power_175: none or provide your own sensor to reflect the correct power flowing through your inverter.

**Comment by Legnava89** [comment]
Hello, could you please add a temperature function to aux load 1 and 2?
Marked on the photo
Thank you very much for your time and answer.
![teplota](https://github.com/slipx06/sunsynk-power-flow-card/assets/145229528/e065007b-bf69-489b-97a8-9ab1d0d646c4)

**Comment by slipx06** [comment]
@Legnava89 this has been added to the v2.8 https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v2.8.0
