### ISSUE TITLE
Add ability to change caption/font size for the sensor text

### ISSUE THREAD

**Issue by alfwro13** [slipx06/sunsynk-power-flow-card#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the current version text under sensors such us: DAILY SOLAR/LEFT TODAY, DAILY GRID SELL, DAILY GRID BUY, etc are all in upper case which I find difficult to read and there is no option to change the size or font type or case.

### Expected behaviour

there is currently no option to change that behavior

### Possible Solutions

Please add option to change the size and case

### Mode

full

### Context / Reason

In the current implementation text under sensors is in upper case with no option to customize it. That text is difficult to read

**Comment by slipx06** [comment]
Hi. These are not configurable elements. Changing the font size can affect positioning of other card elements and could cause display issues. You can however clone the repo and modify the language file to to change the font case. The font type is inherited from your HA theme.  

https://github.com/slipx06/sunsynk-power-flow-card/blob/master/src/localize/languages/en.json
