### ISSUE TITLE
Micro Inverter Integration

### ISSUE THREAD

**Issue by Cretanios** [slipx06/sunsynk-power-flow-card#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Micro Inverter can not be displayed/integrated

### Expected behaviour

similar to Solar also the micro inverter power (and maybe frequency in off-grid mode)

### Possible Solutions

no

### Mode

lite

### Context / Reason

micro inverters are an official option to us instead of the generator option in the sunsynk/deye inverters

**Comment by slipx06** [comment]
Hi, This is not displayed on the lite version of the card. You can use the AUX input on the full card to display this power

**Comment by chinezbrun** [comment]
also interested on this

**Comment by slipx06** [comment]
@vinaytje94 I've moved you post here

Right now i have updated and adjusted mine with a micro inverter on the aux input. It looks like this
![Screenshot_20231013_210116_Home Assistant](https://github.com/slipx06/sunsynk-power-flow-card/assets/110492139/469d2bb4-20ed-477c-bb01-c07a8d0de036)

**Comment by vinaytje94** [comment]
> @vinaytje94 I've moved your post here
> 
> Right now i have updated and adjusted mine with a micro inverter on the aux input. It looks like this ![Screenshot_20231013_210116_Home Assistant](https://user-images.githubusercontent.com/110492139/275093582-469d2bb4-20ed-477c-bb01-c07a8d0de036.jpg)

It looks like this when the MI is online. I have the SUN-2000WG3 MI from Deye and i used the solarman integration. 
![Screenshot_20231014_082429_Home Assistant](https://github.com/slipx06/sunsynk-power-flow-card/assets/110492139/d5438499-76de-4ea8-a547-d519ee0b69a6)

Got it setup like this

`  show_daily_aux: true
  show_aux: true
  invert_aux: true
  aux_name: MicroInverter
  aux_type: mdi:solar-power-variant
  aux_colour: green
  aux_off_colour: gray
  aux_icon: mdi:solar-power-variant
  aux_loads: 0
  aux_load1_name: MicroInverter
  aux_load2_name: Aux load 2
  aux_load1_icon: mdi:solar-power-variant
  aux_load2_icon: mdi:stove
  animation_speed: 8
  max_power: 2000`

For the aux related inputs i used the sensors from the solarman MI integration
