### ISSUE TITLE
Display multiple batteries data

### ISSUE THREAD

**Issue by chinezbrun** [slipx06/sunsynk-power-flow-card#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have sensors in Home Assistant that gave me the individual batteries data from the bank.
Currently the card can't integrate those sensors.

### Expected behaviour

To have possibility to see multiple batteries on the card. Similar like PV. 
bat 1 soc 1, V1, A1, W1
bat 2 soc2, V1, A1, W2

general bat, average (soc1,2), avg, (v1,2), sum(A1,A2), sum(W1,2)

### Possible Solutions

i.e for two bat
bat 1 soc 1, V1, A1, W1
bat 2 soc2, V1, A1, W2

and the general bat with average (soc1,2), avg, (V1,2), sum(A1,A2), sum(W1,2)

display can be new icons like PV or rows...

### Mode

Both

### Context / Reason

to see the power flow and soc for individual bat too. potential to discover unbalanced bat.

**Comment by slipx06** [comment]
Hi. Its a nice idea but there is no space for this information. If you can suggest some mockup's I'll take a look
