### ISSUE TITLE
Mistakes in Czech language version

### ISSUE THREAD

**Issue by mamo-nick** [slipx06/sunsynk-power-flow-card#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I checked the cs.json file, so there are some mistakes or some raws are not translated.
And autarky item could be translated. 

### Expected behaviour

Right the czech translation
Item "autarky" translated - On raw #31 added translation of Item "autarky"

[cs(.json).txt](https://github.com/slipx06/sunsynk-power-flow-card/files/13056852/cs.json.txt)

### Card Version

2.13

### Home Assistant Version

2023.10.0

**Comment by slipx06** [comment]
OK added to [2.13.1](https://github.com/slipx06/sunsynk-power-flow-card/releases/tag/v2.13.1). Thanks for the Czech updates
